/* Generated by Macrocoder - do not edit */
#define _CRT_SECURE_NO_WARNINGS
#include "md380.h"
#include "crc.h"
#include "md380_tools.h"
#include <assert.h>
#include <stdio.h>

/* Function that decodes a binary record into the structure */
void decodeBinary_ChannelInformation (const t_buffer* buffer, unsigned offsetInOctets, T_ChannelInformation* record)
{
	unsigned ofs = offsetInOctets * 8;
	record->LoneWorker = bitsToNumeric (buffer, ofs + 0, 1);
	record->Squelch = bitsToNumeric (buffer, ofs + 2, 1);
	record->Autoscan = bitsToNumeric (buffer, ofs + 3, 1);
	record->Bandwidth = bitsToNumeric (buffer, ofs + 4, 1);
	record->ChannelMode = bitsToNumeric (buffer, ofs + 6, 2);
	record->Colorcode = bitsToNumeric (buffer, ofs + 8, 4);
	record->RepeaterSlot = bitsToNumeric (buffer, ofs + 12, 2);
	record->RxOnly = bitsToNumeric (buffer, ofs + 14, 1);
	record->AllowTalkaround = bitsToNumeric (buffer, ofs + 15, 1);
	record->DataCallConf = bitsToNumeric (buffer, ofs + 16, 1);
	record->PrivateCallConf = bitsToNumeric (buffer, ofs + 17, 1);
	record->Privacy = bitsToNumeric (buffer, ofs + 18, 2);
	record->PrivacyNo = bitsToNumeric (buffer, ofs + 20, 4);
	record->DisplayPttId = bitsToNumeric (buffer, ofs + 24, 1);
	record->CompressedUdpHdr = bitsToNumeric (buffer, ofs + 25, 1);
	record->EmergencyAlarmAck = bitsToNumeric (buffer, ofs + 28, 1);
	record->RxRefFrequency = bitsToNumeric (buffer, ofs + 30, 2);
	record->AdmintCriteria = bitsToNumeric (buffer, ofs + 32, 2);
	record->Power = bitsToNumeric (buffer, ofs + 34, 1);
	record->Vox = bitsToNumeric (buffer, ofs + 35, 1);
	record->QtReverse = bitsToNumeric (buffer, ofs + 36, 1);
	record->ReverseBurst = bitsToNumeric (buffer, ofs + 37, 1);
	record->TxRefFrequency = bitsToNumeric (buffer, ofs + 38, 2);
	record->ContactName.refLineNo = binaryToNumeric (buffer, ofs + 48, 16);
	record->Tot = bitsToNumeric (buffer, ofs + 66, 6);
	record->TotRekeyDelay = bitsToNumeric (buffer, ofs + 72, 8);
	record->EmergencySystem = bitsToNumeric (buffer, ofs + 82, 6);
	record->ScanList.refLineNo = bitsToNumeric (buffer, ofs + 88, 8);
	record->GroupList.refLineNo = bitsToNumeric (buffer, ofs + 96, 8);
	record->Decode18 = bitsToNumeric (buffer, ofs + 112, 8);
	record->RxFrequency = BCDToNumeric (buffer, ofs + 128, 32);
	record->TxFrequency = BCDToNumeric (buffer, ofs + 160, 32);
	record->CtcssDcsDecode = BCDToNumericForTones (buffer, ofs + 192);
	record->CtcssDcsEncode = BCDToNumericForTones (buffer, ofs + 208);
	record->TxSignalingSyst = bitsToNumeric (buffer, ofs + 237, 3);
	record->RxSignalingSyst = bitsToNumeric (buffer, ofs + 229, 3);
	binaryToUnicode (buffer, ofs + 256, record->Name, 256);
}

/* Function that encodes a structure into a binary record */
void encodeBinary_ChannelInformation (t_buffer* buffer, unsigned offsetInOctets, const T_ChannelInformation* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_ChannelInformation);

	numericToBits (buffer, ofs + 1, 1, 1);
	numericToBits (buffer, ofs + 26, 1, 1);
	numericToBits (buffer, ofs + 40, 195, 8);
	numericToBits (buffer, ofs + 104, 1, 8);
	numericToBits (buffer, ofs + 120, 255, 8);
	numericToBits (buffer, ofs + 240, 255, 8);
	numericToBits (buffer, ofs + 248, 255, 8);
	numericToBits (buffer, ofs + 0, record->LoneWorker, 1);
	numericToBits (buffer, ofs + 2, record->Squelch, 1);
	numericToBits (buffer, ofs + 3, record->Autoscan, 1);
	numericToBits (buffer, ofs + 4, record->Bandwidth, 1);
	numericToBits (buffer, ofs + 6, record->ChannelMode, 2);
	numericToBits (buffer, ofs + 8, record->Colorcode, 4);
	numericToBits (buffer, ofs + 12, record->RepeaterSlot, 2);
	numericToBits (buffer, ofs + 14, record->RxOnly, 1);
	numericToBits (buffer, ofs + 15, record->AllowTalkaround, 1);
	numericToBits (buffer, ofs + 16, record->DataCallConf, 1);
	numericToBits (buffer, ofs + 17, record->PrivateCallConf, 1);
	numericToBits (buffer, ofs + 18, record->Privacy, 2);
	numericToBits (buffer, ofs + 20, record->PrivacyNo, 4);
	numericToBits (buffer, ofs + 24, record->DisplayPttId, 1);
	numericToBits (buffer, ofs + 25, record->CompressedUdpHdr, 1);
	numericToBits (buffer, ofs + 28, record->EmergencyAlarmAck, 1);
	numericToBits (buffer, ofs + 30, record->RxRefFrequency, 2);
	numericToBits (buffer, ofs + 32, record->AdmintCriteria, 2);
	numericToBits (buffer, ofs + 34, record->Power, 1);
	numericToBits (buffer, ofs + 35, record->Vox, 1);
	numericToBits (buffer, ofs + 36, record->QtReverse, 1);
	numericToBits (buffer, ofs + 37, record->ReverseBurst, 1);
	numericToBits (buffer, ofs + 38, record->TxRefFrequency, 2);
	numericToBinary (buffer, ofs + 48, record->ContactName.refLineNo, 16);
	numericToBits (buffer, ofs + 66, record->Tot, 6);
	numericToBits (buffer, ofs + 72, record->TotRekeyDelay, 8);
	numericToBits (buffer, ofs + 82, record->EmergencySystem, 6);
	numericToBits (buffer, ofs + 88, record->ScanList.refLineNo, 8);
	numericToBits (buffer, ofs + 96, record->GroupList.refLineNo, 8);
	numericToBits (buffer, ofs + 112, record->Decode18, 8);
	numericToBCD (buffer, ofs + 128, record->RxFrequency, 32);
	numericToBCD (buffer, ofs + 160, record->TxFrequency, 32);
	numericToBCDForTones (buffer, ofs + 192, record->CtcssDcsDecode);
	numericToBCDForTones (buffer, ofs + 208, record->CtcssDcsEncode);
	numericToBits (buffer, ofs + 237, record->TxSignalingSyst, 3);
	numericToBits (buffer, ofs + 229, record->RxSignalingSyst, 3);
	unicodeToBinary (buffer, ofs + 256, record->Name, 256);
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_ChannelInformation (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0xFF */
	memset (buffer+offsetInOctets, 0xFF, LENGTH_ChannelInformation);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 32, 0, 32);
}

/* Enumeration values for record ChannelInformation, field LoneWorker */
static const FieldEnumerator ENUM_ChannelInformation_LoneWorker [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field Squelch */
static const FieldEnumerator ENUM_ChannelInformation_Squelch [2] = {
	{0x3B8A80B4, "tight", 0},
	{0x218568E4, "normal", 1}
};

/* Enumeration values for record ChannelInformation, field Autoscan */
static const FieldEnumerator ENUM_ChannelInformation_Autoscan [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field Bandwidth */
static const FieldEnumerator ENUM_ChannelInformation_Bandwidth [2] = {
	{0x1388BC29, "12.5", 0},
	{0x7418F1CD, "25.0", 1}
};

/* Enumeration values for record ChannelInformation, field ChannelMode */
static const FieldEnumerator ENUM_ChannelInformation_ChannelMode [2] = {
	{0xCB484DD7, "digital", 2},
	{0xA78C95C1, "analog", 1}
};

/* Enumeration values for record ChannelInformation, field RepeaterSlot */
static const FieldEnumerator ENUM_ChannelInformation_RepeaterSlot [2] = {
	{0x50A6156C, "slot1", 1},
	{0xC9AF44D6, "slot2", 2}
};

/* Enumeration values for record ChannelInformation, field RxOnly */
static const FieldEnumerator ENUM_ChannelInformation_RxOnly [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field AllowTalkaround */
static const FieldEnumerator ENUM_ChannelInformation_AllowTalkaround [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field DataCallConf */
static const FieldEnumerator ENUM_ChannelInformation_DataCallConf [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field PrivateCallConf */
static const FieldEnumerator ENUM_ChannelInformation_PrivateCallConf [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field Privacy */
static const FieldEnumerator ENUM_ChannelInformation_Privacy [3] = {
	{0x7F9000CF, "none", 0},
	{0x90797553, "basic", 1},
	{0xA5685A2E, "enhanced", 2}
};

/* Enumeration values for record ChannelInformation, field DisplayPttId */
static const FieldEnumerator ENUM_ChannelInformation_DisplayPttId [2] = {
	{0x09B629C8, "on", 0},
	{0x2BBC5D43, "off", 1}
};

/* Enumeration values for record ChannelInformation, field CompressedUdpHdr */
static const FieldEnumerator ENUM_ChannelInformation_CompressedUdpHdr [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field EmergencyAlarmAck */
static const FieldEnumerator ENUM_ChannelInformation_EmergencyAlarmAck [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field RxRefFrequency */
static const FieldEnumerator ENUM_ChannelInformation_RxRefFrequency [3] = {
	{0x928878A1, "low", 0},
	{0xC67345B7, "medium", 1},
	{0xF105E455, "high", 2}
};

/* Enumeration values for record ChannelInformation, field AdmintCriteria */
static const FieldEnumerator ENUM_ChannelInformation_AdmintCriteria [4] = {
	{0xA6A43C1B, "always", 0},
	{0xFA8AFE0F, "chFree", 1},
	{0x123441DB, "CTCSS/DCS", 2},
	{0xEADBDCED, "colorCode", 3}
};

/* Enumeration values for record ChannelInformation, field Power */
static const FieldEnumerator ENUM_ChannelInformation_Power [2] = {
	{0x928878A1, "low", 0},
	{0xF105E455, "high", 1}
};

/* Enumeration values for record ChannelInformation, field Vox */
static const FieldEnumerator ENUM_ChannelInformation_Vox [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field QtReverse */
static const FieldEnumerator ENUM_ChannelInformation_QtReverse [2] = {
	{0xEBAEDAE2, "180", 0},
	{0x11413268, "120", 1}
};

/* Enumeration values for record ChannelInformation, field ReverseBurst */
static const FieldEnumerator ENUM_ChannelInformation_ReverseBurst [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field TxRefFrequency */
static const FieldEnumerator ENUM_ChannelInformation_TxRefFrequency [3] = {
	{0x928878A1, "low", 0},
	{0xC67345B7, "medium", 1},
	{0xF105E455, "high", 2}
};

/* Enumeration values for record ChannelInformation, field ContactName */
static const FieldEnumerator ENUM_ChannelInformation_ContactName [1] = {
	{0x7F9000CF, "none", 0}
};

/* Enumeration values for record ChannelInformation, field ScanList */
static const FieldEnumerator ENUM_ChannelInformation_ScanList [1] = {
	{0x7F9000CF, "none", 0}
};

/* Enumeration values for record ChannelInformation, field GroupList */
static const FieldEnumerator ENUM_ChannelInformation_GroupList [1] = {
	{0x7F9000CF, "none", 0}
};

/* Enumeration values for record ChannelInformation, field Decode18 */
static const FieldEnumerator ENUM_ChannelInformation_Decode18 [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record ChannelInformation, field CtcssDcsDecode */
static const FieldEnumerator ENUM_ChannelInformation_CtcssDcsDecode [259] = {
	{0x7F9000CF, "none", 0},
	{0x13CADCFA, "T67.0", 670},
	{0x805DA04A, "T69.3", 693},
	{0xD6277F89, "T71.9", 719},
	{0xAE5DC1DF, "T74.4", 744},
	{0xAB76BB9F, "T77.0", 770},
	{0x3F8C0336, "T79.7", 797},
	{0x85B49DAD, "T82.5", 825},
	{0xF7FCBBBE, "T85.4", 854},
	{0x8823187B, "T88.5", 885},
	{0x3F4E4491, "T91.5", 915},
	{0x4734FAC7, "T94.8", 948},
	{0x4CC408B5, "T97.4", 974},
	{0x44AE5BF3, "T100.0", 1000},
	{0x36821125, "T103.5", 1035},
	{0xAFEF2C5A, "T107.2", 1072},
	{0x85CE8432, "T110.9", 1109},
	{0xF5C01C78, "T114.8", 1148},
	{0xFCDAE51C, "T118.8", 1188},
	{0xECE12D21, "T123.0", 1230},
	{0x72E1D447, "T127.3", 1273},
	{0x59021618, "T131.8", 1318},
	{0x22FC7C20, "T136.5", 1365},
	{0x5307F729, "T141.3", 1413},
	{0x214FD13A, "T146.2", 1462},
	{0x75DF05EF, "T151.4", 1514},
	{0xE99942D0, "T156.7", 1567},
	{0x727A187C, "T159.8", 1598},
	{0x8C4FB16D, "T162.2", 1622},
	{0x1764324B, "T165.5", 1655},
	{0x1D56AA0E, "T167.9", 1679},
	{0x41B258C7, "T171.3", 1713},
	{0xD5E45521, "T173.8", 1738},
	{0x453F2475, "T177.3", 1773},
	{0xAF74E061, "T179.9", 1799},
	{0xF33639CA, "T183.5", 1835},
	{0x6B996E82, "T186.2", 1862},
	{0xF717F037, "T189.9", 1899},
	{0x34F94825, "T192.8", 1928},
	{0xD448CDFE, "T196.6", 1966},
	{0x461DDB79, "T199.5", 1995},
	{0x71226BF5, "T203.5", 2035},
	{0x77E9A91E, "T206.5", 2065},
	{0x25D6D3E5, "T210.7", 2107},
	{0xC2A62768, "T218.1", 2181},
	{0x31A8BEE0, "T225.7", 2257},
	{0xD1D1E2B1, "T229.1", 2291},
	{0xFA9E95A1, "T233.6", 2336},
	{0x83755471, "T241.8", 2418},
	{0xADD980AB, "T250.3", 2503},
	{0x44DE495B, "T254.1", 2541},
	{0x2335C6A0, "D023N", 131095},
	{0x756F6126, "D025N", 131097},
	{0x5E4232E5, "D026N", 131098},
	{0x10C1CE15, "D031N", 131103},
	{0x3BEC9DD6, "D032N", 131104},
	{0x5F8058D2, "D036N", 131108},
	{0x27B8BA12, "D043N", 131115},
	{0x43D47F16, "D047N", 131119},
	{0x144CB2A7, "D051N", 131123},
	{0x267AD025, "D053N", 131125},
	{0x693B46E2, "D054N", 131126},
	{0x7266C9FA, "D065N", 131137},
	{0x17C866C9, "D071N", 131143},
	{0x3CE5350A, "D072N", 131144},
	{0x25FE044B, "D073N", 131145},
	{0x6ABF928C, "D074N", 131146},
	{0xD68E895B, "D114N", 131186},
	{0xCF95B81A, "D115N", 131187},
	{0xE4B8EBD9, "D116N", 131188},
	{0x82929084, "D122N", 131194},
	{0xCDD30643, "D125N", 131197},
	{0xA87DA970, "D131N", 131203},
	{0x8350FAB3, "D132N", 131204},
	{0xD50A5D35, "D134N", 131206},
	{0x9F04DD77, "D143N", 131215},
	{0xC95E7AF1, "D145N", 131217},
	{0x87DD8601, "D152N", 131224},
	{0xC89C10C6, "D155N", 131227},
	{0xE3B14305, "D156N", 131228},
	{0x859B3858, "D162N", 131234},
	{0xCADAAE9F, "D165N", 131237},
	{0x8459526F, "D172N", 131244},
	{0xD203F5E9, "D174N", 131246},
	{0xDCE27DC3, "D205N", 131277},
	{0x92618133, "D212N", 131284},
	{0x893C0E2B, "D223N", 131295},
	{0xDF66A9AD, "D225N", 131297},
	{0xF44BFA6E, "D226N", 131298},
	{0x8DB17299, "D243N", 131315},
	{0xC2F0E45E, "D244N", 131316},
	{0xDBEBD51F, "D245N", 131317},
	{0xF0C686DC, "D246N", 131318},
	{0xBE457A2C, "D251N", 131323},
	{0x956829EF, "D252N", 131324},
	{0xDA29BF28, "D255N", 131327},
	{0xBC03C475, "D261N", 131333},
	{0x8E35A6F7, "D263N", 131335},
	{0xD86F0171, "D265N", 131337},
	{0xF34252B2, "D266N", 131338},
	{0xBDC1AE42, "D271N", 131343},
	{0xC0B65A07, "D274N", 131346},
	{0x4F734965, "D306N", 131378},
	{0x01F0B595, "D311N", 131383},
	{0x659C7091, "D315N", 131387},
	{0x67DACEC8, "D325N", 131397},
	{0x027461FB, "D331N", 131403},
	{0x29593238, "D332N", 131404},
	{0x350D15FC, "D343N", 131415},
	{0x487AE1B9, "D346N", 131418},
	{0x06F91D49, "D351N", 131423},
	{0x49B88B8E, "D356N", 131428},
	{0x79C85755, "D364N", 131436},
	{0x60D36614, "D365N", 131437},
	{0x057DC927, "D371N", 131443},
	{0x9C278D2C, "D411N", 131483},
	{0xB70ADEEF, "D412N", 131484},
	{0xAE11EFAE, "D413N", 131485},
	{0xAC5751F7, "D423N", 131495},
	{0x9FA35942, "D431N", 131503},
	{0xB48E0A81, "D432N", 131504},
	{0xFE808AC3, "D445N", 131517},
	{0xD5ADD900, "D446N", 131518},
	{0xB0037633, "D452N", 131524},
	{0xE659D1B5, "D454N", 131526},
	{0xFF42E0F4, "D455N", 131527},
	{0xB245C86A, "D462N", 131534},
	{0xE41F6FEC, "D464N", 131536},
	{0xFD045EAD, "D465N", 131537},
	{0xD6290D6E, "D466N", 131538},
	{0x176FE2FC, "D503N", 131575},
	{0x6A1816B9, "D506N", 131578},
	{0x6BDA7C8E, "D516N", 131588},
	{0x14EB3692, "D523N", 131595},
	{0x699CC2D7, "D526N", 131598},
	{0x0C326DE4, "D532N", 131604},
	{0x6D11BE65, "D546N", 131618},
	{0x45B839C8, "D565N", 131637},
	{0x78ADB957, "D606N", 131678},
	{0x1D031664, "D612N", 131684},
	{0x491F0FBB, "D624N", 131696},
	{0x62325C78, "D627N", 131699},
	{0x35AA91C9, "D631N", 131703},
	{0x1E87C20A, "D632N", 131704},
	{0x4C50193E, "D654N", 131726},
	{0x184C00E1, "D662N", 131734},
	{0x4E16A767, "D664N", 131736},
	{0xBD662A77, "D703N", 131775},
	{0xA5BF7101, "D712N", 131784},
	{0xBEE2FE19, "D723N", 131795},
	{0x8D16F6AC, "D731N", 131803},
	{0xA63BA56F, "D732N", 131804},
	{0xF06102E9, "D734N", 131806},
	{0xBA6F82AB, "D743N", 131815},
	{0xF4EC7E5B, "D754N", 131826},
	{0xBD515303, "D023I", 196631},
	{0xEB0BF485, "D025I", 196633},
	{0xC026A746, "D026I", 196634},
	{0x8EA55BB6, "D031I", 196639},
	{0xA5880875, "D032I", 196640},
	{0xC1E4CD71, "D036I", 196644},
	{0xB9DC2FB1, "D043I", 196651},
	{0xDDB0EAB5, "D047I", 196655},
	{0x8A282704, "D051I", 196659},
	{0xB81E4586, "D053I", 196661},
	{0xF75FD341, "D054I", 196662},
	{0xEC025C59, "D065I", 196673},
	{0x89ACF36A, "D071I", 196679},
	{0xA281A0A9, "D072I", 196680},
	{0xBB9A91E8, "D073I", 196681},
	{0xF4DB072F, "D074I", 196682},
	{0x48EA1CF8, "D114I", 196722},
	{0x51F12DB9, "D115I", 196723},
	{0x7ADC7E7A, "D116I", 196724},
	{0x1CF60527, "D122I", 196730},
	{0x53B793E0, "D125I", 196733},
	{0x36193CD3, "D131I", 196739},
	{0x1D346F10, "D132I", 196740},
	{0x4B6EC896, "D134I", 196742},
	{0x016048D4, "D143I", 196751},
	{0x573AEF52, "D145I", 196753},
	{0x19B913A2, "D152I", 196760},
	{0x56F88565, "D155I", 196763},
	{0x7DD5D6A6, "D156I", 196764},
	{0x1BFFADFB, "D162I", 196770},
	{0x54BE3B3C, "D165I", 196773},
	{0x1A3DC7CC, "D172I", 196780},
	{0x4C67604A, "D174I", 196782},
	{0x4286E860, "D205I", 196813},
	{0x0C051490, "D212I", 196820},
	{0x17589B88, "D223I", 196831},
	{0x41023C0E, "D225I", 196833},
	{0x6A2F6FCD, "D226I", 196834},
	{0x13D5E73A, "D243I", 196851},
	{0x5C9471FD, "D244I", 196852},
	{0x458F40BC, "D245I", 196853},
	{0x6EA2137F, "D246I", 196854},
	{0x2021EF8F, "D251I", 196859},
	{0x0B0CBC4C, "D252I", 196860},
	{0x444D2A8B, "D255I", 196863},
	{0x226751D6, "D261I", 196869},
	{0x10513354, "D263I", 196871},
	{0x460B94D2, "D265I", 196873},
	{0x6D26C711, "D266I", 196874},
	{0x23A53BE1, "D271I", 196879},
	{0x5ED2CFA4, "D274I", 196882},
	{0xD117DCC6, "D306I", 196914},
	{0x9F942036, "D311I", 196919},
	{0xFBF8E532, "D315I", 196923},
	{0xF9BE5B6B, "D325I", 196933},
	{0x9C10F458, "D331I", 196939},
	{0xB73DA79B, "D332I", 196940},
	{0xAB69805F, "D343I", 196951},
	{0xD61E741A, "D346I", 196954},
	{0x989D88EA, "D351I", 196959},
	{0xD7DC1E2D, "D356I", 196964},
	{0xE7ACC2F6, "D364I", 196972},
	{0xFEB7F3B7, "D365I", 196973},
	{0x9B195C84, "D371I", 196979},
	{0x0243188F, "D411I", 197019},
	{0x296E4B4C, "D412I", 197020},
	{0x30757A0D, "D413I", 197021},
	{0x3233C454, "D423I", 197031},
	{0x01C7CCE1, "D431I", 197039},
	{0x2AEA9F22, "D432I", 197040},
	{0x60E41F60, "D445I", 197053},
	{0x4BC94CA3, "D446I", 197054},
	{0x2E67E390, "D452I", 197060},
	{0x783D4416, "D454I", 197062},
	{0x61267557, "D455I", 197063},
	{0x2C215DC9, "D462I", 197070},
	{0x7A7BFA4F, "D464I", 197072},
	{0x6360CB0E, "D465I", 197073},
	{0x484D98CD, "D466I", 197074},
	{0x890B775F, "D503I", 197111},
	{0xF47C831A, "D506I", 197114},
	{0xF5BEE92D, "D516I", 197124},
	{0x8A8FA331, "D523I", 197131},
	{0xF7F85774, "D526I", 197134},
	{0x9256F847, "D532I", 197140},
	{0xF3752BC6, "D546I", 197154},
	{0xDBDCAC6B, "D565I", 197173},
	{0xE6C92CF4, "D606I", 197214},
	{0x836783C7, "D612I", 197220},
	{0xD77B9A18, "D624I", 197232},
	{0xFC56C9DB, "D627I", 197235},
	{0xABCE046A, "D631I", 197239},
	{0x80E357A9, "D632I", 197240},
	{0xD2348C9D, "D654I", 197262},
	{0x86289542, "D662I", 197270},
	{0xD07232C4, "D664I", 197272},
	{0x2302BFD4, "D703I", 197311},
	{0x3BDBE4A2, "D712I", 197320},
	{0x20866BBA, "D723I", 197331},
	{0x1372630F, "D731I", 197339},
	{0x385F30CC, "D732I", 197340},
	{0x6E05974A, "D734I", 197342},
	{0x240B1708, "D743I", 197351},
	{0x6A88EBF8, "D754I", 197362}
};

/* Enumeration values for record ChannelInformation, field CtcssDcsEncode */
static const FieldEnumerator ENUM_ChannelInformation_CtcssDcsEncode [259] = {
	{0x7F9000CF, "none", 0},
	{0x13CADCFA, "T67.0", 670},
	{0x805DA04A, "T69.3", 693},
	{0xD6277F89, "T71.9", 719},
	{0xAE5DC1DF, "T74.4", 744},
	{0xAB76BB9F, "T77.0", 770},
	{0x3F8C0336, "T79.7", 797},
	{0x85B49DAD, "T82.5", 825},
	{0xF7FCBBBE, "T85.4", 854},
	{0x8823187B, "T88.5", 885},
	{0x3F4E4491, "T91.5", 915},
	{0x4734FAC7, "T94.8", 948},
	{0x4CC408B5, "T97.4", 974},
	{0x44AE5BF3, "T100.0", 1000},
	{0x36821125, "T103.5", 1035},
	{0xAFEF2C5A, "T107.2", 1072},
	{0x85CE8432, "T110.9", 1109},
	{0xF5C01C78, "T114.8", 1148},
	{0xFCDAE51C, "T118.8", 1188},
	{0xECE12D21, "T123.0", 1230},
	{0x72E1D447, "T127.3", 1273},
	{0x59021618, "T131.8", 1318},
	{0x22FC7C20, "T136.5", 1365},
	{0x5307F729, "T141.3", 1413},
	{0x214FD13A, "T146.2", 1462},
	{0x75DF05EF, "T151.4", 1514},
	{0xE99942D0, "T156.7", 1567},
	{0x727A187C, "T159.8", 1598},
	{0x8C4FB16D, "T162.2", 1622},
	{0x1764324B, "T165.5", 1655},
	{0x1D56AA0E, "T167.9", 1679},
	{0x41B258C7, "T171.3", 1713},
	{0xD5E45521, "T173.8", 1738},
	{0x453F2475, "T177.3", 1773},
	{0xAF74E061, "T179.9", 1799},
	{0xF33639CA, "T183.5", 1835},
	{0x6B996E82, "T186.2", 1862},
	{0xF717F037, "T189.9", 1899},
	{0x34F94825, "T192.8", 1928},
	{0xD448CDFE, "T196.6", 1966},
	{0x461DDB79, "T199.5", 1995},
	{0x71226BF5, "T203.5", 2035},
	{0x77E9A91E, "T206.5", 2065},
	{0x25D6D3E5, "T210.7", 2107},
	{0xC2A62768, "T218.1", 2181},
	{0x31A8BEE0, "T225.7", 2257},
	{0xD1D1E2B1, "T229.1", 2291},
	{0xFA9E95A1, "T233.6", 2336},
	{0x83755471, "T241.8", 2418},
	{0xADD980AB, "T250.3", 2503},
	{0x44DE495B, "T254.1", 2541},
	{0x2335C6A0, "D023N", 131095},
	{0x756F6126, "D025N", 131097},
	{0x5E4232E5, "D026N", 131098},
	{0x10C1CE15, "D031N", 131103},
	{0x3BEC9DD6, "D032N", 131104},
	{0x5F8058D2, "D036N", 131108},
	{0x27B8BA12, "D043N", 131115},
	{0x43D47F16, "D047N", 131119},
	{0x144CB2A7, "D051N", 131123},
	{0x267AD025, "D053N", 131125},
	{0x693B46E2, "D054N", 131126},
	{0x7266C9FA, "D065N", 131137},
	{0x17C866C9, "D071N", 131143},
	{0x3CE5350A, "D072N", 131144},
	{0x25FE044B, "D073N", 131145},
	{0x6ABF928C, "D074N", 131146},
	{0xD68E895B, "D114N", 131186},
	{0xCF95B81A, "D115N", 131187},
	{0xE4B8EBD9, "D116N", 131188},
	{0x82929084, "D122N", 131194},
	{0xCDD30643, "D125N", 131197},
	{0xA87DA970, "D131N", 131203},
	{0x8350FAB3, "D132N", 131204},
	{0xD50A5D35, "D134N", 131206},
	{0x9F04DD77, "D143N", 131215},
	{0xC95E7AF1, "D145N", 131217},
	{0x87DD8601, "D152N", 131224},
	{0xC89C10C6, "D155N", 131227},
	{0xE3B14305, "D156N", 131228},
	{0x859B3858, "D162N", 131234},
	{0xCADAAE9F, "D165N", 131237},
	{0x8459526F, "D172N", 131244},
	{0xD203F5E9, "D174N", 131246},
	{0xDCE27DC3, "D205N", 131277},
	{0x92618133, "D212N", 131284},
	{0x893C0E2B, "D223N", 131295},
	{0xDF66A9AD, "D225N", 131297},
	{0xF44BFA6E, "D226N", 131298},
	{0x8DB17299, "D243N", 131315},
	{0xC2F0E45E, "D244N", 131316},
	{0xDBEBD51F, "D245N", 131317},
	{0xF0C686DC, "D246N", 131318},
	{0xBE457A2C, "D251N", 131323},
	{0x956829EF, "D252N", 131324},
	{0xDA29BF28, "D255N", 131327},
	{0xBC03C475, "D261N", 131333},
	{0x8E35A6F7, "D263N", 131335},
	{0xD86F0171, "D265N", 131337},
	{0xF34252B2, "D266N", 131338},
	{0xBDC1AE42, "D271N", 131343},
	{0xC0B65A07, "D274N", 131346},
	{0x4F734965, "D306N", 131378},
	{0x01F0B595, "D311N", 131383},
	{0x659C7091, "D315N", 131387},
	{0x67DACEC8, "D325N", 131397},
	{0x027461FB, "D331N", 131403},
	{0x29593238, "D332N", 131404},
	{0x350D15FC, "D343N", 131415},
	{0x487AE1B9, "D346N", 131418},
	{0x06F91D49, "D351N", 131423},
	{0x49B88B8E, "D356N", 131428},
	{0x79C85755, "D364N", 131436},
	{0x60D36614, "D365N", 131437},
	{0x057DC927, "D371N", 131443},
	{0x9C278D2C, "D411N", 131483},
	{0xB70ADEEF, "D412N", 131484},
	{0xAE11EFAE, "D413N", 131485},
	{0xAC5751F7, "D423N", 131495},
	{0x9FA35942, "D431N", 131503},
	{0xB48E0A81, "D432N", 131504},
	{0xFE808AC3, "D445N", 131517},
	{0xD5ADD900, "D446N", 131518},
	{0xB0037633, "D452N", 131524},
	{0xE659D1B5, "D454N", 131526},
	{0xFF42E0F4, "D455N", 131527},
	{0xB245C86A, "D462N", 131534},
	{0xE41F6FEC, "D464N", 131536},
	{0xFD045EAD, "D465N", 131537},
	{0xD6290D6E, "D466N", 131538},
	{0x176FE2FC, "D503N", 131575},
	{0x6A1816B9, "D506N", 131578},
	{0x6BDA7C8E, "D516N", 131588},
	{0x14EB3692, "D523N", 131595},
	{0x699CC2D7, "D526N", 131598},
	{0x0C326DE4, "D532N", 131604},
	{0x6D11BE65, "D546N", 131618},
	{0x45B839C8, "D565N", 131637},
	{0x78ADB957, "D606N", 131678},
	{0x1D031664, "D612N", 131684},
	{0x491F0FBB, "D624N", 131696},
	{0x62325C78, "D627N", 131699},
	{0x35AA91C9, "D631N", 131703},
	{0x1E87C20A, "D632N", 131704},
	{0x4C50193E, "D654N", 131726},
	{0x184C00E1, "D662N", 131734},
	{0x4E16A767, "D664N", 131736},
	{0xBD662A77, "D703N", 131775},
	{0xA5BF7101, "D712N", 131784},
	{0xBEE2FE19, "D723N", 131795},
	{0x8D16F6AC, "D731N", 131803},
	{0xA63BA56F, "D732N", 131804},
	{0xF06102E9, "D734N", 131806},
	{0xBA6F82AB, "D743N", 131815},
	{0xF4EC7E5B, "D754N", 131826},
	{0xBD515303, "D023I", 196631},
	{0xEB0BF485, "D025I", 196633},
	{0xC026A746, "D026I", 196634},
	{0x8EA55BB6, "D031I", 196639},
	{0xA5880875, "D032I", 196640},
	{0xC1E4CD71, "D036I", 196644},
	{0xB9DC2FB1, "D043I", 196651},
	{0xDDB0EAB5, "D047I", 196655},
	{0x8A282704, "D051I", 196659},
	{0xB81E4586, "D053I", 196661},
	{0xF75FD341, "D054I", 196662},
	{0xEC025C59, "D065I", 196673},
	{0x89ACF36A, "D071I", 196679},
	{0xA281A0A9, "D072I", 196680},
	{0xBB9A91E8, "D073I", 196681},
	{0xF4DB072F, "D074I", 196682},
	{0x48EA1CF8, "D114I", 196722},
	{0x51F12DB9, "D115I", 196723},
	{0x7ADC7E7A, "D116I", 196724},
	{0x1CF60527, "D122I", 196730},
	{0x53B793E0, "D125I", 196733},
	{0x36193CD3, "D131I", 196739},
	{0x1D346F10, "D132I", 196740},
	{0x4B6EC896, "D134I", 196742},
	{0x016048D4, "D143I", 196751},
	{0x573AEF52, "D145I", 196753},
	{0x19B913A2, "D152I", 196760},
	{0x56F88565, "D155I", 196763},
	{0x7DD5D6A6, "D156I", 196764},
	{0x1BFFADFB, "D162I", 196770},
	{0x54BE3B3C, "D165I", 196773},
	{0x1A3DC7CC, "D172I", 196780},
	{0x4C67604A, "D174I", 196782},
	{0x4286E860, "D205I", 196813},
	{0x0C051490, "D212I", 196820},
	{0x17589B88, "D223I", 196831},
	{0x41023C0E, "D225I", 196833},
	{0x6A2F6FCD, "D226I", 196834},
	{0x13D5E73A, "D243I", 196851},
	{0x5C9471FD, "D244I", 196852},
	{0x458F40BC, "D245I", 196853},
	{0x6EA2137F, "D246I", 196854},
	{0x2021EF8F, "D251I", 196859},
	{0x0B0CBC4C, "D252I", 196860},
	{0x444D2A8B, "D255I", 196863},
	{0x226751D6, "D261I", 196869},
	{0x10513354, "D263I", 196871},
	{0x460B94D2, "D265I", 196873},
	{0x6D26C711, "D266I", 196874},
	{0x23A53BE1, "D271I", 196879},
	{0x5ED2CFA4, "D274I", 196882},
	{0xD117DCC6, "D306I", 196914},
	{0x9F942036, "D311I", 196919},
	{0xFBF8E532, "D315I", 196923},
	{0xF9BE5B6B, "D325I", 196933},
	{0x9C10F458, "D331I", 196939},
	{0xB73DA79B, "D332I", 196940},
	{0xAB69805F, "D343I", 196951},
	{0xD61E741A, "D346I", 196954},
	{0x989D88EA, "D351I", 196959},
	{0xD7DC1E2D, "D356I", 196964},
	{0xE7ACC2F6, "D364I", 196972},
	{0xFEB7F3B7, "D365I", 196973},
	{0x9B195C84, "D371I", 196979},
	{0x0243188F, "D411I", 197019},
	{0x296E4B4C, "D412I", 197020},
	{0x30757A0D, "D413I", 197021},
	{0x3233C454, "D423I", 197031},
	{0x01C7CCE1, "D431I", 197039},
	{0x2AEA9F22, "D432I", 197040},
	{0x60E41F60, "D445I", 197053},
	{0x4BC94CA3, "D446I", 197054},
	{0x2E67E390, "D452I", 197060},
	{0x783D4416, "D454I", 197062},
	{0x61267557, "D455I", 197063},
	{0x2C215DC9, "D462I", 197070},
	{0x7A7BFA4F, "D464I", 197072},
	{0x6360CB0E, "D465I", 197073},
	{0x484D98CD, "D466I", 197074},
	{0x890B775F, "D503I", 197111},
	{0xF47C831A, "D506I", 197114},
	{0xF5BEE92D, "D516I", 197124},
	{0x8A8FA331, "D523I", 197131},
	{0xF7F85774, "D526I", 197134},
	{0x9256F847, "D532I", 197140},
	{0xF3752BC6, "D546I", 197154},
	{0xDBDCAC6B, "D565I", 197173},
	{0xE6C92CF4, "D606I", 197214},
	{0x836783C7, "D612I", 197220},
	{0xD77B9A18, "D624I", 197232},
	{0xFC56C9DB, "D627I", 197235},
	{0xABCE046A, "D631I", 197239},
	{0x80E357A9, "D632I", 197240},
	{0xD2348C9D, "D654I", 197262},
	{0x86289542, "D662I", 197270},
	{0xD07232C4, "D664I", 197272},
	{0x2302BFD4, "D703I", 197311},
	{0x3BDBE4A2, "D712I", 197320},
	{0x20866BBA, "D723I", 197331},
	{0x1372630F, "D731I", 197339},
	{0x385F30CC, "D732I", 197340},
	{0x6E05974A, "D734I", 197342},
	{0x240B1708, "D743I", 197351},
	{0x6A88EBF8, "D754I", 197362}
};

/* Field description table for record ChannelInformation */
FieldDescriptor DESC_ChannelInformation [FIELDS_ChannelInformation] = {
	{0x99140DF7, BL_integer, "LoneWorker", 2, ENUM_ChannelInformation_LoneWorker},
	{0xF12C4068, BL_integer, "Squelch", 2, ENUM_ChannelInformation_Squelch},
	{0xA9154339, BL_integer, "Autoscan", 2, ENUM_ChannelInformation_Autoscan},
	{0x8A09D56F, BL_integer, "Bandwidth", 2, ENUM_ChannelInformation_Bandwidth},
	{0x87048995, BL_integer, "ChannelMode", 2, ENUM_ChannelInformation_ChannelMode},
	{0xEADBDCED, BL_integer, "Colorcode", 0, NULL},
	{0x209D242D, BL_integer, "RepeaterSlot", 2, ENUM_ChannelInformation_RepeaterSlot},
	{0xFF174A2B, BL_integer, "RxOnly", 2, ENUM_ChannelInformation_RxOnly},
	{0xE983887C, BL_integer, "AllowTalkaround", 2, ENUM_ChannelInformation_AllowTalkaround},
	{0x10878B35, BL_integer, "DataCallConf", 2, ENUM_ChannelInformation_DataCallConf},
	{0x85751120, BL_integer, "PrivateCallConf", 2, ENUM_ChannelInformation_PrivateCallConf},
	{0xC3841908, BL_integer, "Privacy", 3, ENUM_ChannelInformation_Privacy},
	{0xCB18C953, BL_integer, "PrivacyNo", 0, NULL},
	{0xA0FA0860, BL_integer, "DisplayPttId", 2, ENUM_ChannelInformation_DisplayPttId},
	{0x143B9C53, BL_integer, "CompressedUdpHdr", 2, ENUM_ChannelInformation_CompressedUdpHdr},
	{0xA7105E25, BL_integer, "EmergencyAlarmAck", 2, ENUM_ChannelInformation_EmergencyAlarmAck},
	{0xCF305C5D, BL_integer, "RxRefFrequency", 3, ENUM_ChannelInformation_RxRefFrequency},
	{0x221B80F9, BL_integer, "AdmintCriteria", 4, ENUM_ChannelInformation_AdmintCriteria},
	{0xAB8A01A0, BL_integer, "Power", 2, ENUM_ChannelInformation_Power},
	{0x13864396, BL_integer, "Vox", 2, ENUM_ChannelInformation_Vox},
	{0x1ED0123B, BL_integer, "QtReverse", 2, ENUM_ChannelInformation_QtReverse},
	{0xAF544755, BL_integer, "ReverseBurst", 2, ENUM_ChannelInformation_ReverseBurst},
	{0x37F217EB, BL_integer, "TxRefFrequency", 3, ENUM_ChannelInformation_TxRefFrequency},
	{0xEE7206C4, BL_integer, "ContactName", 1, ENUM_ChannelInformation_ContactName},
	{0x19B4DBD3, BL_integer, "Tot", 0, NULL},
	{0x89D6E7F6, BL_integer, "TotRekeyDelay", 0, NULL},
	{0xC37BE5EA, BL_integer, "EmergencySystem", 0, NULL},
	{0x7D852DB5, BL_integer, "ScanList", 1, ENUM_ChannelInformation_ScanList},
	{0x8A31099B, BL_integer, "GroupList", 1, ENUM_ChannelInformation_GroupList},
	{0x690859B1, BL_integer, "Decode18", 2, ENUM_ChannelInformation_Decode18},
	{0xE821330F, BL_integer, "RxFrequency", 0, NULL},
	{0x0094F94C, BL_integer, "TxFrequency", 0, NULL},
	{0x68B59605, BL_integer, "CtcssDcsDecode", 259, ENUM_ChannelInformation_CtcssDcsDecode},
	{0xD43974B1, BL_integer, "CtcssDcsEncode", 259, ENUM_ChannelInformation_CtcssDcsEncode},
	{0x3C8FCF1F, BL_integer, "TxSignalingSyst", 0, NULL},
	{0x1E751BED, BL_integer, "RxSignalingSyst", 0, NULL},
	{0x5E237E06, BL_unicode, "Name", 0, NULL}
};

/* Function that decodes a binary record into the structure */
void decodeBinary_DigitalContact (const t_buffer* buffer, unsigned offsetInOctets, T_DigitalContact* record)
{
	unsigned ofs = offsetInOctets * 8;
	record->CallId = binaryToNumeric (buffer, ofs + 0, 24);
	record->CallReceiveTone = bitsToNumeric (buffer, ofs + 26, 1);
	record->CallType = bitsToNumeric (buffer, ofs + 30, 2);
	binaryToUnicode (buffer, ofs + 32, record->Name, 256);
}

/* Function that encodes a structure into a binary record */
void encodeBinary_DigitalContact (t_buffer* buffer, unsigned offsetInOctets, const T_DigitalContact* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_DigitalContact);

	numericToBits (buffer, ofs + 24, 3, 2);
	numericToBinary (buffer, ofs + 0, record->CallId, 24);
	numericToBits (buffer, ofs + 26, record->CallReceiveTone, 1);
	numericToBits (buffer, ofs + 30, record->CallType, 2);
	unicodeToBinary (buffer, ofs + 32, record->Name, 256);
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_DigitalContact (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0xFF */
	memset (buffer+offsetInOctets, 0xFF, LENGTH_DigitalContact);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 4, 0, 32);
}

/* Enumeration values for record DigitalContact, field CallReceiveTone */
static const FieldEnumerator ENUM_DigitalContact_CallReceiveTone [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record DigitalContact, field CallType */
static const FieldEnumerator ENUM_DigitalContact_CallType [3] = {
	{0x6DC044C5, "group", 1},
	{0xD206C1D1, "private", 2},
	{0x3B1871DD, "all", 3}
};

/* Field description table for record DigitalContact */
FieldDescriptor DESC_DigitalContact [FIELDS_DigitalContact] = {
	{0x552D8DFA, BL_integer, "CallId", 0, NULL},
	{0xB3C14049, BL_integer, "CallReceiveTone", 2, ENUM_DigitalContact_CallReceiveTone},
	{0x98E9E238, BL_integer, "CallType", 3, ENUM_DigitalContact_CallType},
	{0x5E237E06, BL_unicode, "Name", 0, NULL}
};

/* Function that decodes a binary record into the structure */
void decodeBinary_DigitalRxGroupList (const t_buffer* buffer, unsigned offsetInOctets, T_DigitalRxGroupList* record)
{
	unsigned ofs = offsetInOctets * 8;
	binaryToUnicode (buffer, ofs + 0, record->Name, 256);
	
	{
		unsigned zz;
		for (zz=0; zz<32; zz++) {
			record->ContactMember[zz].refLineNo = binaryToNumeric (buffer, ofs + 256+16*zz, 16);
		}
	}
	
}

/* Function that encodes a structure into a binary record */
void encodeBinary_DigitalRxGroupList (t_buffer* buffer, unsigned offsetInOctets, const T_DigitalRxGroupList* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_DigitalRxGroupList);

	unicodeToBinary (buffer, ofs + 0, record->Name, 256);
	
	{
		unsigned kk;
		for (kk=0; kk<32; kk++) {
			numericToBinary (buffer, ofs + 256 + 16*kk, record->ContactMember[kk].refLineNo, 16);
		}
	}
	
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_DigitalRxGroupList (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0x00 */
	memset (buffer+offsetInOctets, 0x00, LENGTH_DigitalRxGroupList);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 0, 0, 32);
}

/* Field description table for record DigitalRxGroupList */
FieldDescriptor DESC_DigitalRxGroupList [FIELDS_DigitalRxGroupList] = {
	{0x5E237E06, BL_unicode, "Name", 0, NULL},
	{0x9BA87CD2, BL_integer, "ContactMember01", 0, NULL},
	{0x02A12D68, BL_integer, "ContactMember02", 0, NULL},
	{0x75A61DFE, BL_integer, "ContactMember03", 0, NULL},
	{0xEBC2885D, BL_integer, "ContactMember04", 0, NULL},
	{0x9CC5B8CB, BL_integer, "ContactMember05", 0, NULL},
	{0x05CCE971, BL_integer, "ContactMember06", 0, NULL},
	{0x72CBD9E7, BL_integer, "ContactMember07", 0, NULL},
	{0xE274C476, BL_integer, "ContactMember08", 0, NULL},
	{0x9573F4E0, BL_integer, "ContactMember09", 0, NULL},
	{0xF5B47D05, BL_integer, "ContactMember10", 0, NULL},
	{0x82B34D93, BL_integer, "ContactMember11", 0, NULL},
	{0x1BBA1C29, BL_integer, "ContactMember12", 0, NULL},
	{0x6CBD2CBF, BL_integer, "ContactMember13", 0, NULL},
	{0xF2D9B91C, BL_integer, "ContactMember14", 0, NULL},
	{0x85DE898A, BL_integer, "ContactMember15", 0, NULL},
	{0x1CD7D830, BL_integer, "ContactMember16", 0, NULL},
	{0x6BD0E8A6, BL_integer, "ContactMember17", 0, NULL},
	{0xFB6FF537, BL_integer, "ContactMember18", 0, NULL},
	{0x8C68C5A1, BL_integer, "ContactMember19", 0, NULL},
	{0xDE992EC6, BL_integer, "ContactMember20", 0, NULL},
	{0xA99E1E50, BL_integer, "ContactMember21", 0, NULL},
	{0x30974FEA, BL_integer, "ContactMember22", 0, NULL},
	{0x47907F7C, BL_integer, "ContactMember23", 0, NULL},
	{0xD9F4EADF, BL_integer, "ContactMember24", 0, NULL},
	{0xAEF3DA49, BL_integer, "ContactMember25", 0, NULL},
	{0x37FA8BF3, BL_integer, "ContactMember26", 0, NULL},
	{0x40FDBB65, BL_integer, "ContactMember27", 0, NULL},
	{0xD042A6F4, BL_integer, "ContactMember28", 0, NULL},
	{0xA7459662, BL_integer, "ContactMember29", 0, NULL},
	{0xC7821F87, BL_integer, "ContactMember30", 0, NULL},
	{0xB0852F11, BL_integer, "ContactMember31", 0, NULL},
	{0x298C7EAB, BL_integer, "ContactMember32", 0, NULL}
};

/* Function that decodes a binary record into the structure */
void decodeBinary_GeneralSettings (const t_buffer* buffer, unsigned offsetInOctets, T_GeneralSettings* record)
{
	unsigned ofs = offsetInOctets * 8;
	binaryToUnicode (buffer, ofs + 0, record->InfoScreenLine1, 160);
	binaryToUnicode (buffer, ofs + 160, record->InfoScreenLine2, 160);
	record->MonitorType = bitsToNumeric (buffer, ofs + 515, 1);
	record->DisableAllLeds = bitsToNumeric (buffer, ofs + 517, 1);
	record->TalkPermitTone = bitsToNumeric (buffer, ofs + 520, 2);
	record->PasswordAndLockEnable = bitsToNumeric (buffer, ofs + 522, 1);
	record->CHFreeIndicationTone = bitsToNumeric (buffer, ofs + 523, 1);
	record->DisableAllTone = bitsToNumeric (buffer, ofs + 525, 1);
	record->SaveModeReceive = bitsToNumeric (buffer, ofs + 526, 1);
	record->SavePreamble = bitsToNumeric (buffer, ofs + 527, 1);
	record->IntroScreen = bitsToNumeric (buffer, ofs + 531, 1);
	record->RadioId = binaryToNumeric (buffer, ofs + 544, 24);
	record->TxPreamble = bitsToNumeric (buffer, ofs + 576, 8);
	record->GroupCallHangTime = bitsToNumeric (buffer, ofs + 584, 8);
	record->PrivateCallHangTime = bitsToNumeric (buffer, ofs + 592, 8);
	record->VoxSensitivity = bitsToNumeric (buffer, ofs + 600, 8);
	record->RxLowBatteryInterval = bitsToNumeric (buffer, ofs + 624, 8);
	record->CallAlertTone = bitsToNumeric (buffer, ofs + 632, 8);
	record->LoneWorkerRespTime = bitsToNumeric (buffer, ofs + 640, 8);
	record->LoneWorkerReminderTime = bitsToNumeric (buffer, ofs + 648, 8);
	record->ScanDigitalHangTime = bitsToNumeric (buffer, ofs + 664, 8);
	record->ScanAnalogHangTime = bitsToNumeric (buffer, ofs + 672, 8);
	record->Unknown1 = bitsToNumeric (buffer, ofs + 680, 8);
	record->KeypadLockTime = bitsToNumeric (buffer, ofs + 688, 8);
	record->Mode = bitsToNumeric (buffer, ofs + 696, 8);
	record->PowerOnPassword = RevBCDToNumeric (buffer, ofs + 704, 32);
	record->RadioProgPassowrd = RevBCDToNumeric (buffer, ofs + 736, 32);
	asciiBinaryToUnicode (buffer, ofs + 768, record->PcProgPassword, 64);
	binaryToUnicode (buffer, ofs + 896, record->RadioName, 256);
}

/* Function that encodes a structure into a binary record */
void encodeBinary_GeneralSettings (t_buffer* buffer, unsigned offsetInOctets, const T_GeneralSettings* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_GeneralSettings);

	unicodeToBinary (buffer, ofs + 0, record->InfoScreenLine1, 160);
	unicodeToBinary (buffer, ofs + 160, record->InfoScreenLine2, 160);
	numericToBits (buffer, ofs + 515, record->MonitorType, 1);
	numericToBits (buffer, ofs + 517, record->DisableAllLeds, 1);
	numericToBits (buffer, ofs + 520, record->TalkPermitTone, 2);
	numericToBits (buffer, ofs + 522, record->PasswordAndLockEnable, 1);
	numericToBits (buffer, ofs + 523, record->CHFreeIndicationTone, 1);
	numericToBits (buffer, ofs + 525, record->DisableAllTone, 1);
	numericToBits (buffer, ofs + 526, record->SaveModeReceive, 1);
	numericToBits (buffer, ofs + 527, record->SavePreamble, 1);
	numericToBits (buffer, ofs + 531, record->IntroScreen, 1);
	numericToBinary (buffer, ofs + 544, record->RadioId, 24);
	numericToBits (buffer, ofs + 576, record->TxPreamble, 8);
	numericToBits (buffer, ofs + 584, record->GroupCallHangTime, 8);
	numericToBits (buffer, ofs + 592, record->PrivateCallHangTime, 8);
	numericToBits (buffer, ofs + 600, record->VoxSensitivity, 8);
	numericToBits (buffer, ofs + 624, record->RxLowBatteryInterval, 8);
	numericToBits (buffer, ofs + 632, record->CallAlertTone, 8);
	numericToBits (buffer, ofs + 640, record->LoneWorkerRespTime, 8);
	numericToBits (buffer, ofs + 648, record->LoneWorkerReminderTime, 8);
	numericToBits (buffer, ofs + 664, record->ScanDigitalHangTime, 8);
	numericToBits (buffer, ofs + 672, record->ScanAnalogHangTime, 8);
	numericToBits (buffer, ofs + 680, record->Unknown1, 8);
	numericToBits (buffer, ofs + 688, record->KeypadLockTime, 8);
	numericToBits (buffer, ofs + 696, record->Mode, 8);
	numericToRevBCD (buffer, ofs + 704, record->PowerOnPassword, 32);
	numericToRevBCD (buffer, ofs + 736, record->RadioProgPassowrd, 32);
	unicodeToAsciiBinary (buffer, ofs + 768, record->PcProgPassword, 64);
	unicodeToBinary (buffer, ofs + 896, record->RadioName, 256);
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_GeneralSettings (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0xFF */
	memset (buffer+offsetInOctets, 0xFF, LENGTH_GeneralSettings);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 0, 0, 20);
	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 20, 0, 20);
	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 96, 0, 8);
	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 112, 0, 32);
}

/* Enumeration values for record GeneralSettings, field MonitorType */
static const FieldEnumerator ENUM_GeneralSettings_MonitorType [2] = {
	{0x3BAC798C, "silent", 0},
	{0xA47083A4, "open", 1}
};

/* Enumeration values for record GeneralSettings, field DisableAllLeds */
static const FieldEnumerator ENUM_GeneralSettings_DisableAllLeds [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record GeneralSettings, field TalkPermitTone */
static const FieldEnumerator ENUM_GeneralSettings_TalkPermitTone [4] = {
	{0x7F9000CF, "none", 0},
	{0xCB484DD7, "digital", 1},
	{0xA78C95C1, "analog", 2},
	{0xFBDA3911, "both", 3}
};

/* Enumeration values for record GeneralSettings, field PasswordAndLockEnable */
static const FieldEnumerator ENUM_GeneralSettings_PasswordAndLockEnable [2] = {
	{0x2BBC5D43, "off", 1},
	{0x09B629C8, "on", 0}
};

/* Enumeration values for record GeneralSettings, field CHFreeIndicationTone */
static const FieldEnumerator ENUM_GeneralSettings_CHFreeIndicationTone [2] = {
	{0x2BBC5D43, "off", 1},
	{0x09B629C8, "on", 0}
};

/* Enumeration values for record GeneralSettings, field DisableAllTone */
static const FieldEnumerator ENUM_GeneralSettings_DisableAllTone [2] = {
	{0x2BBC5D43, "off", 1},
	{0x09B629C8, "on", 0}
};

/* Enumeration values for record GeneralSettings, field SaveModeReceive */
static const FieldEnumerator ENUM_GeneralSettings_SaveModeReceive [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record GeneralSettings, field SavePreamble */
static const FieldEnumerator ENUM_GeneralSettings_SavePreamble [2] = {
	{0x2BBC5D43, "off", 0},
	{0x09B629C8, "on", 1}
};

/* Enumeration values for record GeneralSettings, field IntroScreen */
static const FieldEnumerator ENUM_GeneralSettings_IntroScreen [2] = {
	{0x762B8694, "charstring", 0},
	{0x16DB4F89, "picture", 1}
};

/* Enumeration values for record GeneralSettings, field KeypadLockTime */
static const FieldEnumerator ENUM_GeneralSettings_KeypadLockTime [4] = {
	{0x2AE4F0CF, "5s", 1},
	{0xCCA240C0, "10s", 2},
	{0xB1D5B485, "15s", 3},
	{0x10DBBEC4, "manual", 255}
};

/* Enumeration values for record GeneralSettings, field Mode */
static const FieldEnumerator ENUM_GeneralSettings_Mode [2] = {
	{0x2F811705, "mr", 0},
	{0x4C60C3F1, "ch", 255}
};

/* Field description table for record GeneralSettings */
FieldDescriptor DESC_GeneralSettings [FIELDS_GeneralSettings] = {
	{0xB1C6E56A, BL_unicode, "InfoScreenLine1", 0, NULL},
	{0x28CFB4D0, BL_unicode, "InfoScreenLine2", 0, NULL},
	{0x4423A6A5, BL_integer, "MonitorType", 2, ENUM_GeneralSettings_MonitorType},
	{0x012866F4, BL_integer, "DisableAllLeds", 2, ENUM_GeneralSettings_DisableAllLeds},
	{0x09C0FCB9, BL_integer, "TalkPermitTone", 4, ENUM_GeneralSettings_TalkPermitTone},
	{0x3C470C00, BL_integer, "PasswordAndLockEnable", 2, ENUM_GeneralSettings_PasswordAndLockEnable},
	{0xA9B4D975, BL_integer, "CHFreeIndicationTone", 2, ENUM_GeneralSettings_CHFreeIndicationTone},
	{0x9729C189, BL_integer, "DisableAllTone", 2, ENUM_GeneralSettings_DisableAllTone},
	{0xABF771D6, BL_integer, "SaveModeReceive", 2, ENUM_GeneralSettings_SaveModeReceive},
	{0x09BBFCCD, BL_integer, "SavePreamble", 2, ENUM_GeneralSettings_SavePreamble},
	{0xDF7AD539, BL_integer, "IntroScreen", 2, ENUM_GeneralSettings_IntroScreen},
	{0xB2C45235, BL_integer, "RadioId", 0, NULL},
	{0x0A103D33, BL_integer, "TxPreamble", 0, NULL},
	{0xC639746F, BL_integer, "GroupCallHangTime", 0, NULL},
	{0x2DED4A9B, BL_integer, "PrivateCallHangTime", 0, NULL},
	{0x5FC4678E, BL_integer, "VoxSensitivity", 0, NULL},
	{0x42CC8820, BL_integer, "RxLowBatteryInterval", 0, NULL},
	{0xA0B5F1C8, BL_integer, "CallAlertTone", 0, NULL},
	{0xB8458B40, BL_integer, "LoneWorkerRespTime", 0, NULL},
	{0xDA6F744A, BL_integer, "LoneWorkerReminderTime", 0, NULL},
	{0x7E95842B, BL_integer, "ScanDigitalHangTime", 0, NULL},
	{0x310D9AA5, BL_integer, "ScanAnalogHangTime", 0, NULL},
	{0x86719E03, BL_integer, "Unknown1", 0, NULL},
	{0xAD010737, BL_integer, "KeypadLockTime", 4, ENUM_GeneralSettings_KeypadLockTime},
	{0x97CA47AB, BL_integer, "Mode", 2, ENUM_GeneralSettings_Mode},
	{0x3E53F415, BL_integer, "PowerOnPassword", 0, NULL},
	{0x609621CF, BL_integer, "RadioProgPassowrd", 0, NULL},
	{0x42E73CF8, BL_unicode, "PcProgPassword", 0, NULL},
	{0x101A283A, BL_unicode, "RadioName", 0, NULL}
};

/* Function that decodes a binary record into the structure */
void decodeBinary_ScanList (const t_buffer* buffer, unsigned offsetInOctets, T_ScanList* record)
{
	unsigned ofs = offsetInOctets * 8;
	binaryToUnicode (buffer, ofs + 0, record->Name, 256);
	record->PriorityCh1.refLineNo = binaryToNumeric (buffer, ofs + 256, 16);
	record->PriorityCh2.refLineNo = binaryToNumeric (buffer, ofs + 272, 16);
	record->TXDesignatedCh.refLineNo = binaryToNumeric (buffer, ofs + 288, 16);
	record->SignHoldTime = bitsToNumeric (buffer, ofs + 312, 8);
	record->PrioSamplTime = bitsToNumeric (buffer, ofs + 320, 8);
	
	{
		unsigned zz;
		for (zz=0; zz<31; zz++) {
			record->ChannelMember[zz].refLineNo = binaryToNumeric (buffer, ofs + 336+16*zz, 16);
		}
	}
	
}

/* Function that encodes a structure into a binary record */
void encodeBinary_ScanList (t_buffer* buffer, unsigned offsetInOctets, const T_ScanList* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_ScanList);

	unicodeToBinary (buffer, ofs + 0, record->Name, 256);
	numericToBinary (buffer, ofs + 256, record->PriorityCh1.refLineNo, 16);
	numericToBinary (buffer, ofs + 272, record->PriorityCh2.refLineNo, 16);
	numericToBinary (buffer, ofs + 288, record->TXDesignatedCh.refLineNo, 16);
	numericToBits (buffer, ofs + 312, record->SignHoldTime, 8);
	numericToBits (buffer, ofs + 320, record->PrioSamplTime, 8);
	
	{
		unsigned kk;
		for (kk=0; kk<31; kk++) {
			numericToBinary (buffer, ofs + 336 + 16*kk, record->ChannelMember[kk].refLineNo, 16);
		}
	}
	
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_ScanList (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0x00 */
	memset (buffer+offsetInOctets, 0x00, LENGTH_ScanList);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 0, 0, 32);
}

/* Enumeration values for record ScanList, field PriorityCh1 */
static const FieldEnumerator ENUM_ScanList_PriorityCh1 [2] = {
	{0x7F9000CF, "none", 65535},
	{0x98A9BF86, "selected", 0}
};

/* Enumeration values for record ScanList, field PriorityCh2 */
static const FieldEnumerator ENUM_ScanList_PriorityCh2 [2] = {
	{0x7F9000CF, "none", 65535},
	{0x98A9BF86, "selected", 0}
};

/* Enumeration values for record ScanList, field TXDesignatedCh */
static const FieldEnumerator ENUM_ScanList_TXDesignatedCh [2] = {
	{0x7F9000CF, "none", 65535},
	{0x4ADBA9A0, "last", 0}
};

/* Field description table for record ScanList */
FieldDescriptor DESC_ScanList [FIELDS_ScanList] = {
	{0x5E237E06, BL_unicode, "Name", 0, NULL},
	{0x66109137, BL_integer, "PriorityCh1", 2, ENUM_ScanList_PriorityCh1},
	{0xFF19C08D, BL_integer, "PriorityCh2", 2, ENUM_ScanList_PriorityCh2},
	{0xA5243F30, BL_integer, "TXDesignatedCh", 2, ENUM_ScanList_TXDesignatedCh},
	{0x87A6A61E, BL_integer, "SignHoldTime", 0, NULL},
	{0x50BA70E9, BL_integer, "PrioSamplTime", 0, NULL},
	{0xB6C46252, BL_integer, "ChannelMember01", 0, NULL},
	{0x2FCD33E8, BL_integer, "ChannelMember02", 0, NULL},
	{0x58CA037E, BL_integer, "ChannelMember03", 0, NULL},
	{0xC6AE96DD, BL_integer, "ChannelMember04", 0, NULL},
	{0xB1A9A64B, BL_integer, "ChannelMember05", 0, NULL},
	{0x28A0F7F1, BL_integer, "ChannelMember06", 0, NULL},
	{0x5FA7C767, BL_integer, "ChannelMember07", 0, NULL},
	{0xCF18DAF6, BL_integer, "ChannelMember08", 0, NULL},
	{0xB81FEA60, BL_integer, "ChannelMember09", 0, NULL},
	{0xD8D86385, BL_integer, "ChannelMember10", 0, NULL},
	{0xAFDF5313, BL_integer, "ChannelMember11", 0, NULL},
	{0x36D602A9, BL_integer, "ChannelMember12", 0, NULL},
	{0x41D1323F, BL_integer, "ChannelMember13", 0, NULL},
	{0xDFB5A79C, BL_integer, "ChannelMember14", 0, NULL},
	{0xA8B2970A, BL_integer, "ChannelMember15", 0, NULL},
	{0x31BBC6B0, BL_integer, "ChannelMember16", 0, NULL},
	{0x46BCF626, BL_integer, "ChannelMember17", 0, NULL},
	{0xD603EBB7, BL_integer, "ChannelMember18", 0, NULL},
	{0xA104DB21, BL_integer, "ChannelMember19", 0, NULL},
	{0xF3F53046, BL_integer, "ChannelMember20", 0, NULL},
	{0x84F200D0, BL_integer, "ChannelMember21", 0, NULL},
	{0x1DFB516A, BL_integer, "ChannelMember22", 0, NULL},
	{0x6AFC61FC, BL_integer, "ChannelMember23", 0, NULL},
	{0xF498F45F, BL_integer, "ChannelMember24", 0, NULL},
	{0x839FC4C9, BL_integer, "ChannelMember25", 0, NULL},
	{0x1A969573, BL_integer, "ChannelMember26", 0, NULL},
	{0x6D91A5E5, BL_integer, "ChannelMember27", 0, NULL},
	{0xFD2EB874, BL_integer, "ChannelMember28", 0, NULL},
	{0x8A2988E2, BL_integer, "ChannelMember29", 0, NULL},
	{0xEAEE0107, BL_integer, "ChannelMember30", 0, NULL},
	{0x9DE93191, BL_integer, "ChannelMember31", 0, NULL}
};

/* Function that decodes a binary record into the structure */
void decodeBinary_TextMessage (const t_buffer* buffer, unsigned offsetInOctets, T_TextMessage* record)
{
	unsigned ofs = offsetInOctets * 8;
	binaryToUnicode (buffer, ofs + 0, record->Text, 2304);
}

/* Function that encodes a structure into a binary record */
void encodeBinary_TextMessage (t_buffer* buffer, unsigned offsetInOctets, const T_TextMessage* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_TextMessage);

	unicodeToBinary (buffer, ofs + 0, record->Text, 2304);
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_TextMessage (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0x00 */
	memset (buffer+offsetInOctets, 0x00, LENGTH_TextMessage);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 0, 0, 288);
}

/* Field description table for record TextMessage */
FieldDescriptor DESC_TextMessage [FIELDS_TextMessage] = {
	{0x3B8BA7C7, BL_unicode, "Text", 0, NULL}
};

/* Function that decodes a binary record into the structure */
void decodeBinary_ZoneInformation (const t_buffer* buffer, unsigned offsetInOctets, T_ZoneInformation* record)
{
	unsigned ofs = offsetInOctets * 8;
	binaryToUnicode (buffer, ofs + 0, record->Name, 256);
	
	{
		unsigned zz;
		for (zz=0; zz<16; zz++) {
			record->ChannelMember[zz].refLineNo = binaryToNumeric (buffer, ofs + 256+16*zz, 16);
		}
	}
	
}

/* Function that encodes a structure into a binary record */
void encodeBinary_ZoneInformation (t_buffer* buffer, unsigned offsetInOctets, const T_ZoneInformation* record)
{
	unsigned ofs = offsetInOctets * 8;
	
	memset (buffer+offsetInOctets, 0, LENGTH_ZoneInformation);

	unicodeToBinary (buffer, ofs + 0, record->Name, 256);
	
	{
		unsigned kk;
		for (kk=0; kk<16; kk++) {
			numericToBinary (buffer, ofs + 256 + 16*kk, record->ChannelMember[kk].refLineNo, 16);
		}
	}
	
}
/* Function that encodes an empty record into a binary record */
void encodeBinaryEmpty_ZoneInformation (t_buffer* buffer, unsigned offsetInOctets)
{
	/* By default memory is set to 0x00 */
	memset (buffer+offsetInOctets, 0x00, LENGTH_ZoneInformation);

	/* Unicode empty record are encoded as 0 */
	memset (buffer + offsetInOctets + 0, 0, 32);
}

/* Field description table for record ZoneInformation */
FieldDescriptor DESC_ZoneInformation [FIELDS_ZoneInformation] = {
	{0x5E237E06, BL_unicode, "Name", 0, NULL},
	{0xB6C46252, BL_integer, "ChannelMember01", 0, NULL},
	{0x2FCD33E8, BL_integer, "ChannelMember02", 0, NULL},
	{0x58CA037E, BL_integer, "ChannelMember03", 0, NULL},
	{0xC6AE96DD, BL_integer, "ChannelMember04", 0, NULL},
	{0xB1A9A64B, BL_integer, "ChannelMember05", 0, NULL},
	{0x28A0F7F1, BL_integer, "ChannelMember06", 0, NULL},
	{0x5FA7C767, BL_integer, "ChannelMember07", 0, NULL},
	{0xCF18DAF6, BL_integer, "ChannelMember08", 0, NULL},
	{0xB81FEA60, BL_integer, "ChannelMember09", 0, NULL},
	{0xD8D86385, BL_integer, "ChannelMember10", 0, NULL},
	{0xAFDF5313, BL_integer, "ChannelMember11", 0, NULL},
	{0x36D602A9, BL_integer, "ChannelMember12", 0, NULL},
	{0x41D1323F, BL_integer, "ChannelMember13", 0, NULL},
	{0xDFB5A79C, BL_integer, "ChannelMember14", 0, NULL},
	{0xA8B2970A, BL_integer, "ChannelMember15", 0, NULL},
	{0x31BBC6B0, BL_integer, "ChannelMember16", 0, NULL}
};

/* Decode a binary file; its size must be FILE_SIZE_TRDTFile */
void decodeBinary_TRDTFile (const t_buffer* buffer, TRDTFile* container)
{
	unsigned i;
	
	container->ChannelInformation_COUNT = 0;
	
	for (i=0; i<1000; i++) {
		if ((bitsToNumeric (buffer, (OFFSET_ChannelInformation+i*LENGTH_ChannelInformation) * 8 + 128, 8) == 255)) {
			break;
		}
		decodeBinary_ChannelInformation (buffer, OFFSET_ChannelInformation+i*LENGTH_ChannelInformation, container->ChannelInformation+i);
		container->ChannelInformation_COUNT++;
	}
	
	container->DigitalContact_COUNT = 0;
	
	for (i=0; i<1000; i++) {
		if ((bitsToNumeric (buffer, (OFFSET_DigitalContact+i*LENGTH_DigitalContact) * 8 + 0, 8) == 255) && (bitsToNumeric (buffer, (OFFSET_DigitalContact+i*LENGTH_DigitalContact) * 8 + 8, 8) == 255) && (bitsToNumeric (buffer, (OFFSET_DigitalContact+i*LENGTH_DigitalContact) * 8 + 16, 8) == 255)) {
			break;
		}
		decodeBinary_DigitalContact (buffer, OFFSET_DigitalContact+i*LENGTH_DigitalContact, container->DigitalContact+i);
		container->DigitalContact_COUNT++;
	}
	
	container->DigitalRxGroupList_COUNT = 0;
	
	for (i=0; i<250; i++) {
		if ((bitsToNumeric (buffer, (OFFSET_DigitalRxGroupList+i*LENGTH_DigitalRxGroupList) * 8 + 0, 8) == 0)) {
			break;
		}
		decodeBinary_DigitalRxGroupList (buffer, OFFSET_DigitalRxGroupList+i*LENGTH_DigitalRxGroupList, container->DigitalRxGroupList+i);
		container->DigitalRxGroupList_COUNT++;
	}
	
	decodeBinary_GeneralSettings (buffer, OFFSET_GeneralSettings, &container->GeneralSettings);
	
	container->ScanList_COUNT = 0;
	
	for (i=0; i<250; i++) {
		if ((bitsToNumeric (buffer, (OFFSET_ScanList+i*LENGTH_ScanList) * 8 + 0, 8) == 0)) {
			break;
		}
		decodeBinary_ScanList (buffer, OFFSET_ScanList+i*LENGTH_ScanList, container->ScanList+i);
		container->ScanList_COUNT++;
	}
	
	container->TextMessage_COUNT = 0;
	
	for (i=0; i<50; i++) {
		if ((bitsToNumeric (buffer, (OFFSET_TextMessage+i*LENGTH_TextMessage) * 8 + 0, 8) == 0)) {
			break;
		}
		decodeBinary_TextMessage (buffer, OFFSET_TextMessage+i*LENGTH_TextMessage, container->TextMessage+i);
		container->TextMessage_COUNT++;
	}
	
	container->ZoneInformation_COUNT = 0;
	
	for (i=0; i<250; i++) {
		if ((bitsToNumeric (buffer, (OFFSET_ZoneInformation+i*LENGTH_ZoneInformation) * 8 + 0, 8) == 0)) {
			break;
		}
		decodeBinary_ZoneInformation (buffer, OFFSET_ZoneInformation+i*LENGTH_ZoneInformation, container->ZoneInformation+i);
		container->ZoneInformation_COUNT++;
	}

}

/* Encode a binary file; its size must be FILE_SIZE_TRDTFile */
extern void encodeBinary_TRDTFile (t_buffer* buffer, const TRDTFile* container)
{
	unsigned i;
	for (i=0; i<1000; i++) {
		if (i < container->ChannelInformation_COUNT) {
			encodeBinary_ChannelInformation (buffer, OFFSET_ChannelInformation+i*LENGTH_ChannelInformation, container->ChannelInformation+i);
		}
		else {
			encodeBinaryEmpty_ChannelInformation (buffer, OFFSET_ChannelInformation+i*LENGTH_ChannelInformation);
		}
	}
	for (i=0; i<1000; i++) {
		if (i < container->DigitalContact_COUNT) {
			encodeBinary_DigitalContact (buffer, OFFSET_DigitalContact+i*LENGTH_DigitalContact, container->DigitalContact+i);
		}
		else {
			encodeBinaryEmpty_DigitalContact (buffer, OFFSET_DigitalContact+i*LENGTH_DigitalContact);
		}
	}
	for (i=0; i<250; i++) {
		if (i < container->DigitalRxGroupList_COUNT) {
			encodeBinary_DigitalRxGroupList (buffer, OFFSET_DigitalRxGroupList+i*LENGTH_DigitalRxGroupList, container->DigitalRxGroupList+i);
		}
		else {
			encodeBinaryEmpty_DigitalRxGroupList (buffer, OFFSET_DigitalRxGroupList+i*LENGTH_DigitalRxGroupList);
		}
	}
	encodeBinary_GeneralSettings (buffer, OFFSET_GeneralSettings, &container->GeneralSettings);
	for (i=0; i<250; i++) {
		if (i < container->ScanList_COUNT) {
			encodeBinary_ScanList (buffer, OFFSET_ScanList+i*LENGTH_ScanList, container->ScanList+i);
		}
		else {
			encodeBinaryEmpty_ScanList (buffer, OFFSET_ScanList+i*LENGTH_ScanList);
		}
	}
	for (i=0; i<50; i++) {
		if (i < container->TextMessage_COUNT) {
			encodeBinary_TextMessage (buffer, OFFSET_TextMessage+i*LENGTH_TextMessage, container->TextMessage+i);
		}
		else {
			encodeBinaryEmpty_TextMessage (buffer, OFFSET_TextMessage+i*LENGTH_TextMessage);
		}
	}
	for (i=0; i<250; i++) {
		if (i < container->ZoneInformation_COUNT) {
			encodeBinary_ZoneInformation (buffer, OFFSET_ZoneInformation+i*LENGTH_ZoneInformation, container->ZoneInformation+i);
		}
		else {
			encodeBinaryEmpty_ZoneInformation (buffer, OFFSET_ZoneInformation+i*LENGTH_ZoneInformation);
		}
	}

}
