/* Generated by Macrocoder - do not edit */
#define _CRT_SECURE_NO_WARNINGS
#include "md380_tables.h"
#include <string.h>
#include "binlib.h"
#include "crc.h"
#include <assert.h>
#include <stdio.h>

void INIT_MD380Tables (MD380Tables* tables)
{
	INIT_LookupTable (&tables->TAB_ChannelInformation, COUNT_ChannelInformation);
	INIT_LookupTable (&tables->TAB_DigitalContact, COUNT_DigitalContact);
	INIT_LookupTable (&tables->TAB_DigitalRxGroupList, COUNT_DigitalRxGroupList);
	INIT_LookupTable (&tables->TAB_ScanList, COUNT_ScanList);

}

void RESET_MD380Tables (MD380Tables* tables)
{
	RESET_LookupTable (&tables->TAB_ChannelInformation);
	RESET_LookupTable (&tables->TAB_DigitalContact);
	RESET_LookupTable (&tables->TAB_DigitalRxGroupList);
	RESET_LookupTable (&tables->TAB_ScanList);

}

void FREE_MD380Tables (MD380Tables* tables)
{
	FREE_LookupTable (&tables->TAB_ChannelInformation);
	FREE_LookupTable (&tables->TAB_DigitalContact);
	FREE_LookupTable (&tables->TAB_DigitalRxGroupList);
	FREE_LookupTable (&tables->TAB_ScanList);

}

/*==================================================================
	Register a TRDTFile. It register the channel/zone/contact/etc.
	names looking for dupes.
	
	Writes errors on ReportErrorFunc.
	Returns number of errors.
==================================================================*/
int registerContainerNames (MD380Tables* tab, const TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam)
{
	unsigned i;
	int ret;
	char buf [128];
	int noOfViolations = 0;
	
	RESET_MD380Tables (tab);
	
	/*-------------------------------------------------------------------
		ChannelInformation
	-------------------------------------------------------------------*/
	for (i=0; i<container->ChannelInformation_COUNT; i++) {
		ret = ADD_LookupTableUnicode (&tab->TAB_ChannelInformation, container->ChannelInformation[i].Name, i+1);
		if (ret < 0) {
			reportErrorFunc (reportErrorParam, "ChannelInformation", i, "Name", "Lookup table overflow");
			noOfViolations++;
			break;
		}
		else if (ret > 0) {
			sprintf (buf, "Dupe entry (already found at line %d)", ret);
			reportErrorFunc (reportErrorParam, "ChannelInformation", i, "Name", buf);
			noOfViolations++;
		}
	}
	/*-------------------------------------------------------------------
		DigitalContact
	-------------------------------------------------------------------*/
	for (i=0; i<container->DigitalContact_COUNT; i++) {
		ret = ADD_LookupTableNumeric (&tab->TAB_DigitalContact, container->DigitalContact[i].CallId, i+1);
		if (ret < 0) {
			reportErrorFunc (reportErrorParam, "DigitalContact", i, "CallId", "Lookup table overflow");
			noOfViolations++;
			break;
		}
		else if (ret > 0) {
			sprintf (buf, "Dupe entry (already found at line %d)", ret);
			reportErrorFunc (reportErrorParam, "DigitalContact", i, "CallId", buf);
			noOfViolations++;
		}
	}
	/*-------------------------------------------------------------------
		DigitalRxGroupList
	-------------------------------------------------------------------*/
	for (i=0; i<container->DigitalRxGroupList_COUNT; i++) {
		ret = ADD_LookupTableUnicode (&tab->TAB_DigitalRxGroupList, container->DigitalRxGroupList[i].Name, i+1);
		if (ret < 0) {
			reportErrorFunc (reportErrorParam, "DigitalRxGroupList", i, "Name", "Lookup table overflow");
			noOfViolations++;
			break;
		}
		else if (ret > 0) {
			sprintf (buf, "Dupe entry (already found at line %d)", ret);
			reportErrorFunc (reportErrorParam, "DigitalRxGroupList", i, "Name", buf);
			noOfViolations++;
		}
	}
	/*-------------------------------------------------------------------
		ScanList
	-------------------------------------------------------------------*/
	for (i=0; i<container->ScanList_COUNT; i++) {
		ret = ADD_LookupTableUnicode (&tab->TAB_ScanList, container->ScanList[i].Name, i+1);
		if (ret < 0) {
			reportErrorFunc (reportErrorParam, "ScanList", i, "Name", "Lookup table overflow");
			noOfViolations++;
			break;
		}
		else if (ret > 0) {
			sprintf (buf, "Dupe entry (already found at line %d)", ret);
			reportErrorFunc (reportErrorParam, "ScanList", i, "Name", buf);
			noOfViolations++;
		}
	}

	return noOfViolations;
}
