/* Generated by Macrocoder - do not edit */
#ifndef md380_resolve_h
#define md380_resolve_h
#include "md380.h"
#include "md380_valid.h"
#include "md380_tables.h"

/* Resolve the references in a container. Resolves the references read from a CSV, */
/* i.e. it translates the unresolvedCrc into a refLineNo within t_reference  */
extern int resolveReferences(const MD380Tables* tab, TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam);

/* Binds the references in a container. Resolves the references read from a CSV, */
/* i.e. given valid refLineNo within t_reference, it binds the related resolvedName */
extern int bindReferences(TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam);

#endif
