/* Generated by Macrocoder - do not edit */
#define _CRT_SECURE_NO_WARNINGS
#include "md380_csv.h"
#include <stdio.h>
#include <assert.h>
#include "md380_tools.h"

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_ChannelInformation (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_ChannelInformation; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_ChannelInformation[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_ChannelInformation (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_ChannelInformation* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = md380_CsvWriteNumericField (DESC_ChannelInformation+0, record->LoneWorker, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Squelch */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+1, record->Squelch, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Autoscan */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+2, record->Autoscan, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Bandwidth */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+3, record->Bandwidth, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ChannelMode */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+4, record->ChannelMode, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Colorcode */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+5, record->Colorcode, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RepeaterSlot */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+6, record->RepeaterSlot, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RxOnly */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+7, record->RxOnly, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field AllowTalkaround */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+8, record->AllowTalkaround, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field DataCallConf */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+9, record->DataCallConf, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PrivateCallConf */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+10, record->PrivateCallConf, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Privacy */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+11, record->Privacy, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PrivacyNo */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+12, record->PrivacyNo, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field DisplayPttId */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+13, record->DisplayPttId, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CompressedUdpHdr */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+14, record->CompressedUdpHdr, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field EmergencyAlarmAck */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+15, record->EmergencyAlarmAck, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RxRefFrequency */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+16, record->RxRefFrequency, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field AdmintCriteria */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+17, record->AdmintCriteria, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Power */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+18, record->Power, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Vox */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+19, record->Vox, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field QtReverse */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+20, record->QtReverse, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ReverseBurst */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+21, record->ReverseBurst, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TxRefFrequency */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+22, record->TxRefFrequency, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ContactName */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteReferenceFieldNumeric (DESC_ChannelInformation+23, &record->ContactName, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Tot */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+24, record->Tot, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TotRekeyDelay */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+25, record->TotRekeyDelay, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field EmergencySystem */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+26, record->EmergencySystem, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ScanList */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteReferenceFieldUnicode (DESC_ChannelInformation+27, &record->ScanList, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field GroupList */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteReferenceFieldUnicode (DESC_ChannelInformation+28, &record->GroupList, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Decode18 */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+29, record->Decode18, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RxFrequency */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+30, record->RxFrequency, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TxFrequency */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+31, record->TxFrequency, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CtcssDcsDecode */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+32, record->CtcssDcsDecode, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CtcssDcsEncode */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+33, record->CtcssDcsEncode, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TxSignalingSyst */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+34, record->TxSignalingSyst, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RxSignalingSyst */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ChannelInformation+35, record->RxSignalingSyst, "ChannelInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Name */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteTokenUnicode (record->Name, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_DigitalContact (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_DigitalContact; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_DigitalContact[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_DigitalContact (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_DigitalContact* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = md380_CsvWriteNumericField (DESC_DigitalContact+0, record->CallId, "DigitalContact", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CallReceiveTone */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_DigitalContact+1, record->CallReceiveTone, "DigitalContact", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CallType */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_DigitalContact+2, record->CallType, "DigitalContact", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Name */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteTokenUnicode (record->Name, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_DigitalRxGroupList (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_DigitalRxGroupList; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_DigitalRxGroupList[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_DigitalRxGroupList (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_DigitalRxGroupList* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = csvWriteTokenUnicode (record->Name, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ContactMember */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	{
		unsigned kk;
		for (kk=0; kk<32; kk++) {
			if (kk > 0) {
				ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
				if (ret != CSVRET_OK) return ret;
			}
			ret = md380_CsvWriteReferenceFieldNumeric (DESC_DigitalRxGroupList+1, &record->ContactMember[kk], "DigitalRxGroupList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
			if (ret != CSVRET_OK) return ret;
		}
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_GeneralSettings (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_GeneralSettings; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_GeneralSettings[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_GeneralSettings (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_GeneralSettings* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = csvWriteTokenUnicode (record->InfoScreenLine1, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field InfoScreenLine2 */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteTokenUnicode (record->InfoScreenLine2, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field MonitorType */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+2, record->MonitorType, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field DisableAllLeds */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+3, record->DisableAllLeds, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TalkPermitTone */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+4, record->TalkPermitTone, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PasswordAndLockEnable */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+5, record->PasswordAndLockEnable, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CHFreeIndicationTone */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+6, record->CHFreeIndicationTone, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field DisableAllTone */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+7, record->DisableAllTone, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field SaveModeReceive */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+8, record->SaveModeReceive, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field SavePreamble */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+9, record->SavePreamble, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field IntroScreen */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+10, record->IntroScreen, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RadioId */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+11, record->RadioId, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TxPreamble */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+12, record->TxPreamble, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field GroupCallHangTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+13, record->GroupCallHangTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PrivateCallHangTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+14, record->PrivateCallHangTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field VoxSensitivity */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+15, record->VoxSensitivity, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RxLowBatteryInterval */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+16, record->RxLowBatteryInterval, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field CallAlertTone */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+17, record->CallAlertTone, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field LoneWorkerRespTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+18, record->LoneWorkerRespTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field LoneWorkerReminderTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+19, record->LoneWorkerReminderTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ScanDigitalHangTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+20, record->ScanDigitalHangTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ScanAnalogHangTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+21, record->ScanAnalogHangTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Unknown1 */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+22, record->Unknown1, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field KeypadLockTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+23, record->KeypadLockTime, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field Mode */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+24, record->Mode, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PowerOnPassword */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+25, record->PowerOnPassword, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RadioProgPassowrd */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_GeneralSettings+26, record->RadioProgPassowrd, "GeneralSettings", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PcProgPassword */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteTokenUnicode (record->PcProgPassword, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field RadioName */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteTokenUnicode (record->RadioName, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_ScanList (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_ScanList; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_ScanList[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_ScanList (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_ScanList* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = csvWriteTokenUnicode (record->Name, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PriorityCh1 */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteReferenceFieldUnicode (DESC_ScanList+1, &record->PriorityCh1, "ScanList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PriorityCh2 */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteReferenceFieldUnicode (DESC_ScanList+2, &record->PriorityCh2, "ScanList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field TXDesignatedCh */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteReferenceFieldUnicode (DESC_ScanList+3, &record->TXDesignatedCh, "ScanList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field SignHoldTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ScanList+4, record->SignHoldTime, "ScanList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field PrioSamplTime */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = md380_CsvWriteNumericField (DESC_ScanList+5, record->PrioSamplTime, "ScanList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ChannelMember */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	{
		unsigned kk;
		for (kk=0; kk<31; kk++) {
			if (kk > 0) {
				ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
				if (ret != CSVRET_OK) return ret;
			}
			ret = md380_CsvWriteReferenceFieldUnicode (DESC_ScanList+6, &record->ChannelMember[kk], "ScanList", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
			if (ret != CSVRET_OK) return ret;
		}
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_TextMessage (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_TextMessage; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_TextMessage[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_TextMessage (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_TextMessage* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = csvWriteTokenUnicode (record->Text, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}

/* Function that encodes a structure into a binary record. Parameters */
/* and return values are the same of 'csvWriteSeparator' */
int encodeCSVHeader_ZoneInformation (char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter)
{
	int i;
	int ret;
	char* buf = NULL;
	for (i=0; i<FIELDS_ZoneInformation; i++) {
		if (i > 0) {
			ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
			if (ret != CSVRET_OK) goto exitFunc;
		}
		ret = csvWriteToken (DESC_ZoneInformation[i].fieldName, -1, writeBinaryFunc, writeBinaryFuncParameter);
		if (ret != CSVRET_OK) goto exitFunc;
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	
	exitFunc:
	if (buf) binFree (buf);
	return ret;
}

/* Function that encodes a binary empty record. Parameters */
/* and return values are the same of 'csvWriteSeparator */
int encodeCSVRecord_ZoneInformation (unsigned lineNo, char separator, WriteBinaryFunc writeBinaryFunc, void* writeBinaryFuncParameter, const T_ZoneInformation* record, char** errorMessage)
{
	int ret;
	NOWARN_UNUSED(lineNo);
	NOWARN_UNUSED(separator);
	NOWARN_UNUSED(errorMessage);
		ret = csvWriteTokenUnicode (record->Name, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	
	/* Write field ChannelMember */
	ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
	if (ret != CSVRET_OK) return ret;
	{
		unsigned kk;
		for (kk=0; kk<16; kk++) {
			if (kk > 0) {
				ret = csvWriteSeparator (separator, writeBinaryFunc, writeBinaryFuncParameter);
				if (ret != CSVRET_OK) return ret;
			}
			ret = md380_CsvWriteReferenceFieldUnicode (DESC_ZoneInformation+1, &record->ChannelMember[kk], "ZoneInformation", lineNo, writeBinaryFunc, writeBinaryFuncParameter, errorMessage);
			if (ret != CSVRET_OK) return ret;
		}
	}
	ret = csvWriteEndOfLine (writeBinaryFunc, writeBinaryFuncParameter);
	return ret;
}
