/* Generated by Macrocoder - do not edit */
#ifndef md380_valid_h
#define md380_valid_h
#include "md380.h"
#include "md380_tools.h"

/* Validate an entire container */
extern int validateContainer(const TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam);

#endif
