/* Generated by Macrocoder - do not edit */
#define _CRT_SECURE_NO_WARNINGS
#include "md380_resolve.h"
#include <string.h>
#include "binlib.h"
#include "crc.h"
#include <assert.h>
/* Resolve the references in a container. Resolves the references read from a CSV, */
/* i.e. it translates the unresolvedCrc into a refLineNo within t_reference  */
int resolveReferences(const MD380Tables* tab, TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam)
{
	int noOfViolations = 0;
	unsigned i, j;
	
	/* Resolve references for record ChannelInformation */
	for (i=0; i<container->ChannelInformation_COUNT; i++) {
		/* RESOLVE FIELD ContactName */
		if (md380_ResolveReference (DESC_ChannelInformation+23, &container->ChannelInformation[i].ContactName, &tab->TAB_DigitalContact, "ChannelInformation", i, "ContactName", "DigitalContact", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* RESOLVE FIELD ScanList */
		if (md380_ResolveReference (DESC_ChannelInformation+27, &container->ChannelInformation[i].ScanList, &tab->TAB_ScanList, "ChannelInformation", i, "ScanList", "ScanList", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* RESOLVE FIELD GroupList */
		if (md380_ResolveReference (DESC_ChannelInformation+28, &container->ChannelInformation[i].GroupList, &tab->TAB_DigitalRxGroupList, "ChannelInformation", i, "GroupList", "DigitalRxGroupList", reportErrorFunc, reportErrorParam)) noOfViolations++;
	}
	
	/* Resolve references for record DigitalRxGroupList */
	for (i=0; i<container->DigitalRxGroupList_COUNT; i++) {
		for (j=0; j<32; j++) {
			/* RESOLVE FIELD ContactMember */
			if (md380_ResolveReference (DESC_DigitalRxGroupList+1, &container->DigitalRxGroupList[i].ContactMember[j], &tab->TAB_DigitalContact, "DigitalRxGroupList", i, "ContactMember", "DigitalContact", reportErrorFunc, reportErrorParam)) noOfViolations++;
		}
	}
	
	/* Resolve references for record ScanList */
	for (i=0; i<container->ScanList_COUNT; i++) {
		/* RESOLVE FIELD PriorityCh1 */
		if (md380_ResolveReference (DESC_ScanList+1, &container->ScanList[i].PriorityCh1, &tab->TAB_ChannelInformation, "ScanList", i, "PriorityCh1", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* RESOLVE FIELD PriorityCh2 */
		if (md380_ResolveReference (DESC_ScanList+2, &container->ScanList[i].PriorityCh2, &tab->TAB_ChannelInformation, "ScanList", i, "PriorityCh2", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* RESOLVE FIELD TXDesignatedCh */
		if (md380_ResolveReference (DESC_ScanList+3, &container->ScanList[i].TXDesignatedCh, &tab->TAB_ChannelInformation, "ScanList", i, "TXDesignatedCh", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		for (j=0; j<31; j++) {
			/* RESOLVE FIELD ChannelMember */
			if (md380_ResolveReference (DESC_ScanList+6, &container->ScanList[i].ChannelMember[j], &tab->TAB_ChannelInformation, "ScanList", i, "ChannelMember", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		}
	}
	
	/* Resolve references for record ZoneInformation */
	for (i=0; i<container->ZoneInformation_COUNT; i++) {
		for (j=0; j<16; j++) {
			/* RESOLVE FIELD ChannelMember */
			if (md380_ResolveReference (DESC_ZoneInformation+1, &container->ZoneInformation[i].ChannelMember[j], &tab->TAB_ChannelInformation, "ZoneInformation", i, "ChannelMember", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		}
	}

	return noOfViolations;
}
/* Binds the references in a container. Resolves the references read from a CSV, */
/* i.e. given valid refLineNo within t_reference, it binds the related resolvedName */
int bindReferences(TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam)
{
	int noOfViolations = 0;
	unsigned i, j;
	
	/* Bind references for record ChannelInformation */
	for (i=0; i<COUNT_ChannelInformation; i++) {
		/* BIND FIELD ContactName */
		if (md380_BindReferenceNumeric (DESC_ChannelInformation+23, &container->ChannelInformation[i].ContactName, container->DigitalContact_COUNT, container->DigitalContact[(container->ChannelInformation[i].ContactName.refLineNo > 0) ? container->ChannelInformation[i].ContactName.refLineNo-1 : 0].CallId, "ChannelInformation", i, "ContactName", "DigitalContact", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* BIND FIELD ScanList */
		if (md380_BindReferenceUnicode (DESC_ChannelInformation+27, &container->ChannelInformation[i].ScanList, container->ScanList_COUNT, container->ScanList[(container->ChannelInformation[i].ScanList.refLineNo > 0) ? container->ChannelInformation[i].ScanList.refLineNo-1 : 0].Name, "ChannelInformation", i, "ScanList", "ScanList", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* BIND FIELD GroupList */
		if (md380_BindReferenceUnicode (DESC_ChannelInformation+28, &container->ChannelInformation[i].GroupList, container->DigitalRxGroupList_COUNT, container->DigitalRxGroupList[(container->ChannelInformation[i].GroupList.refLineNo > 0) ? container->ChannelInformation[i].GroupList.refLineNo-1 : 0].Name, "ChannelInformation", i, "GroupList", "DigitalRxGroupList", reportErrorFunc, reportErrorParam)) noOfViolations++;
	}
	
	/* Bind references for record DigitalRxGroupList */
	for (i=0; i<COUNT_DigitalRxGroupList; i++) {
		for (j=0; j<32; j++) {
			/* BIND FIELD ContactMember */
			if (md380_BindReferenceNumeric (DESC_DigitalRxGroupList+1, &container->DigitalRxGroupList[i].ContactMember[j], container->DigitalContact_COUNT, container->DigitalContact[(container->DigitalRxGroupList[i].ContactMember[j].refLineNo > 0) ? container->DigitalRxGroupList[i].ContactMember[j].refLineNo-1 : 0].CallId, "DigitalRxGroupList", i, "ContactMember", "DigitalContact", reportErrorFunc, reportErrorParam)) noOfViolations++;
		}
	}
	
	/* Bind references for record ScanList */
	for (i=0; i<COUNT_ScanList; i++) {
		/* BIND FIELD PriorityCh1 */
		if (md380_BindReferenceUnicode (DESC_ScanList+1, &container->ScanList[i].PriorityCh1, container->ChannelInformation_COUNT, container->ChannelInformation[(container->ScanList[i].PriorityCh1.refLineNo > 0) ? container->ScanList[i].PriorityCh1.refLineNo-1 : 0].Name, "ScanList", i, "PriorityCh1", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* BIND FIELD PriorityCh2 */
		if (md380_BindReferenceUnicode (DESC_ScanList+2, &container->ScanList[i].PriorityCh2, container->ChannelInformation_COUNT, container->ChannelInformation[(container->ScanList[i].PriorityCh2.refLineNo > 0) ? container->ScanList[i].PriorityCh2.refLineNo-1 : 0].Name, "ScanList", i, "PriorityCh2", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		/* BIND FIELD TXDesignatedCh */
		if (md380_BindReferenceUnicode (DESC_ScanList+3, &container->ScanList[i].TXDesignatedCh, container->ChannelInformation_COUNT, container->ChannelInformation[(container->ScanList[i].TXDesignatedCh.refLineNo > 0) ? container->ScanList[i].TXDesignatedCh.refLineNo-1 : 0].Name, "ScanList", i, "TXDesignatedCh", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		for (j=0; j<31; j++) {
			/* BIND FIELD ChannelMember */
			if (md380_BindReferenceUnicode (DESC_ScanList+6, &container->ScanList[i].ChannelMember[j], container->ChannelInformation_COUNT, container->ChannelInformation[(container->ScanList[i].ChannelMember[j].refLineNo > 0) ? container->ScanList[i].ChannelMember[j].refLineNo-1 : 0].Name, "ScanList", i, "ChannelMember", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		}
	}
	
	/* Bind references for record ZoneInformation */
	for (i=0; i<COUNT_ZoneInformation; i++) {
		for (j=0; j<16; j++) {
			/* BIND FIELD ChannelMember */
			if (md380_BindReferenceUnicode (DESC_ZoneInformation+1, &container->ZoneInformation[i].ChannelMember[j], container->ChannelInformation_COUNT, container->ChannelInformation[(container->ZoneInformation[i].ChannelMember[j].refLineNo > 0) ? container->ZoneInformation[i].ChannelMember[j].refLineNo-1 : 0].Name, "ZoneInformation", i, "ChannelMember", "ChannelInformation", reportErrorFunc, reportErrorParam)) noOfViolations++;
		}
	}

	return noOfViolations;
}
