/* Generated by Macrocoder - do not edit */
#ifndef md380_cli_h
#define md380_cli_h

typedef struct {
	const char* parameter;
	const char* recordName;
} CliCommands;

#define NO_OF_CLI_COMMANDS 7
extern CliCommands cliCommands[NO_OF_CLI_COMMANDS];


/* Structure mapping the file names to be used for CSV saving */
/* Use INIT_CSVFileNames and FREE_CSVFileNames */
typedef struct {
	char* Path_ChannelInformation;
	char* Path_DigitalContact;
	char* Path_DigitalRxGroupList;
	char* Path_GeneralSettings;
	char* Path_ScanList;
	char* Path_TextMessage;
	char* Path_ZoneInformation;
} CSVFileNames;

/* Initialize a CSVFileNames */
extern void INIT_CSVFileNames(CSVFileNames* fs);

/* Free a CSVFileNames */
extern void FREE_CSVFileNames(CSVFileNames* fs);

#define CLI_PARAMETER_UNKNOWN   0
#define CLI_NOT_ENOUGH_PARAMS  -1
#define CLI_DUPE_PARAMETER     -2
#define CLI_OUT_OF_MEMORY      -3

/* Executes the parsing of the command line. It returns the number */
/* of parameters consumed from the given position or CLI_xxx in case of error */
extern int ParseCommandLine (CSVFileNames* fs, char** argv, int argc);

#endif
