/* Generated by Macrocoder - do not edit */
#ifndef md380_file_h
#define md380_file_h

#include "md380.h"
#include "md380_tools.h"
#include "md380_cli.h"
#include "md380_csv.h"

/* Function that opens a file and saves all the records of 'ChannelInformation'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_ChannelInformation (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'ChannelInformation'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_ChannelInformation (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records of 'DigitalContact'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_DigitalContact (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'DigitalContact'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_DigitalContact (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records of 'DigitalRxGroupList'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_DigitalRxGroupList (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'DigitalRxGroupList'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_DigitalRxGroupList (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records of 'GeneralSettings'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_GeneralSettings (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'GeneralSettings'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_GeneralSettings (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records of 'ScanList'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_ScanList (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'ScanList'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_ScanList (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records of 'TextMessage'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_TextMessage (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'TextMessage'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_TextMessage (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records of 'ZoneInformation'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFile_ZoneInformation (const char* fileName, const TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and reads all the records of 'ZoneInformation'. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFile_ZoneInformation (const char* fileName, TRDTFile* container, char separator, char** errorMessage);

/* Function that opens a file and saves all the records in various CSV files. */
/* The files are saved according to the CSVFileNames structure. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int saveCSVFileAll (const CSVFileNames* csvFileNames, const TRDTFile* container, char separator, char** errorMessage);

/* Function that loads all the records from various CSV files. */
/* The files are loaded according to the CSVFileNames structure. */
/* Returns one of the CSVRET_XXX values. The 'errorMessage' string, */
/* describing the error, is allocated with binAlloc in case of error */
/* and it is to be freed with binFree. */
extern int loadCSVFileAll (const CSVFileNames* csvFileNames, TRDTFile* container, char separator, char** errorMessage);

#endif
