/* Generated by Macrocoder - do not edit */
#ifndef md380_tables_h
#define md380_tables_h
#include "md380.h"
#include "md380_valid.h"

#ifdef __cplusplus
extern "C" {
#endif

/*==================================================================
	LOOKUP TABLES
==================================================================*/
typedef struct {
	
	/* ChannelInformation */
	LookupTable TAB_ChannelInformation;
	
	/* DigitalContact */
	LookupTable TAB_DigitalContact;
	
	/* DigitalRxGroupList */
	LookupTable TAB_DigitalRxGroupList;
	
	/* ScanList */
	LookupTable TAB_ScanList;

} MD380Tables;

extern void INIT_MD380Tables (MD380Tables* tables);
extern void FREE_MD380Tables (MD380Tables* tables);

/*==================================================================
	Register a TRDTFile. It register the channel/zone/contact/etc.
	names looking for dupes.
	
	Writes errors on ReportErrorFunc
==================================================================*/
extern int registerContainerNames (MD380Tables* tab, const TRDTFile* container, ReportErrorFunc reportErrorFunc, void* reportErrorParam);

#ifdef __cplusplus
}
#endif


#endif
